### ISSUE TITLE
Complete Transformation Pack

### ISSUE THREAD

**Issue by cinnamoner** [Elbullazul/Windows-10#1]
Hi CM,

The repo is now structurally great. A few minor touchups could make it even greater. Long story short, it would be nice to have the boot splash, the login screen, the pointer and proper checksumming included as well.

**Comment by Elbullazul** [comment]
Yes, but that artwork is static, and github is designed for dynamic releases. I don't see those two kind of artwork coexisting here. Nonetheless, I can provide download links in the wiki page for a complete pack. Plus, the pointer theme is from another guy. I just provide a link to it.

**Comment by cinnamoner** [comment]
OKAY. Just do what you feel fit. I'm already a happy guy.
In another thread of thought, I wonder whether you figured out an alternative to Allan, aka scorpiox22, flooding the Look with checksums. Don't take me wrong. I appreciate what Allan does (it was me in the first place to initiate the thing), but it's got to be a better way. If I can be of any help concerning checksumming in theory and/or practice, just let me know.

**Comment by cinnamoner** [comment]
Also, it just occurred to me that the W7 theme, initially intended to be a once off, seems to have gotten pretty dynamic. Maybe a retro branch on Git? I'm not kidding. W7 is a splendid theme.

**Comment by Elbullazul** [comment]
Yes, but that means an extra repo... I don't know if I can organize it well enough

**Comment by cinnamoner** [comment]
OKAY, I understand that but at least give it some thought. Thanks.

**Comment by Elbullazul** [comment]
Maybe if I launch a new version of gtk (wich I highly doubt)

**Comment by cinnamoner** [comment]
What's doubt today, oftentimes turns out to be certainty tomorrow. "Never say never", to quote the well-known fictional oil baron from the state of Texas.

**Comment by cinnamoner** [comment]
OKAY. No chatroom. Waiting "service pack" for 0.8 to show up. Thanks.
