### ISSUE TITLE
:checked pseudo class cause warning

### ISSUE THREAD

**Issue by greenlaw110** [Elbullazul/Windows-10#10]
I got the following warning messages when starting gtk app from console:

```
(...): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:138:32: Missing name of pseudo-class

(...): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:164:32: Missing name of pseudo-class

(...): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:190:29: Missing name of pseudo-class
```

The issue is at the following lines in gtk-widgets-assets.css:

![image](https://cloud.githubusercontent.com/assets/216930/12689196/51261da6-c72f-11e5-9c2a-0cf2d04e22b4.png)
![image](https://cloud.githubusercontent.com/assets/216930/12689202/5d0fe700-c72f-11e5-9a8c-88bc7a1f67b7.png)
![image](https://cloud.githubusercontent.com/assets/216930/12689206/65ea912c-c72f-11e5-92db-ef723c7438c2.png)

Removing the `:checked` line will clear the warning messages

**Comment by cinnamoner** [comment]
@greenlaw110 
That's good to know.

**Comment by Elbullazul** [comment]
@greenlaw110 thanks for pointing this out. I'll fix this in next version after checking nothing else breaks.

**Comment by greenlaw110** [comment]
@Elbullazul No worries. I really appreciate your work, it is amazing! Looking forward to seeing your new version. BTW, have you thought about creating a Materialized transformation pack, kind of something like http://papyros.io/

**Comment by Elbullazul** [comment]
@greenlaw110 yeah, I already got asked that question. I'm working on it

**Comment by greenlaw110** [comment]
@Elbullazul you are awesome!

**Comment by Elbullazul** [comment]
@greenlaw110 can you tell me if this is good enough for you? 

http://www.mediafire.com/download/b6krorpaa8fp7mr/WinX_TP_Build_01161.zip

**Warning:** I have to install lxappearance for the moment, but it doesn't break anything. I also have to use a lot of sudo to copy to /usr/share/icons or /themes, but you can review the code without problem.
[Uploading WinX_TP_Build_01161.zip…]()

**Comment by greenlaw110** [comment]
hey I've unpacked the package into my ~/.themes folder and tried it. Here is the screenshot, you need to download to get the clear version: http://ge.tt/97Ao5BX2/v/0

The comments:
1. the ":checked" issue is still there
2. As like the previous version, there is a blue underline under EVERY running application in the task panel, which is a bit annoying. I expect that only the application receive the focus should have the blue underline in the task panel.

**Comment by Elbullazul** [comment]
the upload was interrupted it says...

1) was just an installation pack with the current version
2) winx works like that, sorry. You can, however, replace the asset by a completely transparent svg file named *bottom-item-active-hover.svg* in win_x_folder/cinnamon/panel-assets/

**Comment by cinnamoner** [comment]
@greenlaw110 
Thanks for creating the present thread. Deployment of the whole package is now way easier. And thanks for pointing out those warnings.
@Elbullazul 
Some might like the installer, some might not. Both parties should be granted satisfaction.

**Comment by cinnamoner** [comment]
> thanks for pointing this out. I'll fix this in next version after checking nothing else breaks.

@Elbullazul 
Not a big deal but I'm looking forward to it. Probably not enough to release a new version though.

**Comment by Elbullazul** [comment]
fix included in build for v0.9.1

**Comment by greenlaw110** [comment]
It looks like I still got the issue with v0.9.1:
![image](https://cloud.githubusercontent.com/assets/216930/13097884/354ec2f6-d579-11e5-8223-d5b4f0fb7429.png)

**Comment by Elbullazul** [comment]
@greenlaw110 I forked the preview before the fix. However, it's included on the stable branch.

**Comment by greenlaw110** [comment]
Hey v0.9.4 still have the same issue, is it still a preview version?

![image](https://cloud.githubusercontent.com/assets/216930/13372360/318c2b18-dd94-11e5-9337-58c42cdcb182.png)

**Comment by Elbullazul** [comment]
It's the sacrifice I need to do for the theme to work with Gnome 3.18... :(

if you don't want those errors then search in gtk-widgets for "/*addition" and delete the whole code I added.

Also, delete the whole section for gnome 3.18 in gtk-widgets-assets.css

**Comment by cinnamoner** [comment]
@Elbullazul 
Dealing with conflicting pieces of code is no piece o' cake. I would only code for Cinnamon ("there 'i goes again").

**Comment by cinnamoner** [comment]
@greenlaw110 
Please be understanding. It annoys me too, but this is a unique undertaking. Nobody seems to have endeavored creating a theme so as to cover virtually every DE so far.
