### ISSUE TITLE
Xfce black backgroud window

### ISSUE THREAD

**Issue by midsum** [Elbullazul/Windows-10#11]
hi, love your windows 10 theme, been using it couple a days and i think it's probably the best looking theme for xfce right now..
small issue with the 'add new items' window for the xfce panel. background completely black and as far as i can tell it's the only window to display this behaviour. 
anyway, great work so far hope you keep it up!
![screenshot_2016-02-15_10-35-36](https://cloud.githubusercontent.com/assets/17245996/13043406/a8741d8a-d3d0-11e5-9f9f-701d88d0b080.jpg)

**Comment by Elbullazul** [comment]
yes, I know about this. In fact, I made it look pitch black because before it looked uglier :

https://cloud.githubusercontent.com/assets/2737980/10895126/2619138e-81bb-11e5-8494-424e7d44eb25.png

it's a problem on how xfce organizes apps, because it includes this particular window as a panel class
