### ISSUE TITLE
Highlight line under every taskbar button that track the open window

### ISSUE THREAD

**Issue by greenlaw110** [Elbullazul/Windows-10#12]
See the screen capture:
![image](https://cloud.githubusercontent.com/assets/216930/13097807/8518a2ee-d578-11e5-83c4-dd1837004832.png)

This happened on every version including the latest v0.9.1

**Comment by Elbullazul** [comment]
![windows-10-taskbar](http://www.howtogeek.com/wp-content/uploads/2015/08/536x286xhtf3.png.pagespeed.gp+jp+jw+pj+js+rj+rp+rw+ri+cp+md.ic.9g88cqqC38.png)

However, on earlier versions of the theme, this wasn't the case :
![windows-10-theme-v0.4.2](http://b00merang.weebly.com/uploads/1/6/8/1/16813022/2624054_orig.png)

I suggest you reuse older cinnamon themes found at our archive here : https://github.com/Elbullazul/B00merang-Project/tree/master/Windows%2010%20Themes

Note : use only the Cinnamon theme; you can delete the newer one all right, except for a few color changes and assest it's going to be the same
