### ISSUE TITLE
Gap between start menu and edge of screen.

### ISSUE THREAD

**Issue by Zerophase** [Elbullazul/Windows-10#13]
In the latest release I noticed that the preview image doesn't have a tiny gap, like my screen does. 
I tried zooming in on your image, and couldn't see the wallpaper in that gap.  Could it be an issue with adjusting the menu size based on screen size? I'm on a 1920 x 1080 screen with an aspect ratio of 16:9
 
preview image:

![Image of preview]
(https://cloud.githubusercontent.com/assets/15310985/13188548/1b6554ce-d720-11e5-97d1-4397f21d2773.png)

My desktop image:

![Image of desktop]
(http://i.imgur.com/h7KMPyS.png)

**Comment by cinnamoner** [comment]
This also interests me 'cause I'm switching to 1080p any time now. 

@Zerophase I salute you.

**Comment by greenlaw110** [comment]
Just curious is this theme for mint cinnamon? the task bar looks a little bit different from mine:
![](https://cloud.githubusercontent.com/assets/216930/13097807/8518a2ee-d578-11e5-83c4-dd1837004832.png)

**Comment by Elbullazul** [comment]
@Zerophase I guess it's because you have text beside your menu icon and I don't. 

@Greenlaw110 it's an applet from cinnamon-spices

**Comment by Zerophase** [comment]
@Ellabullazul I'll see if getting rid of the text does anything.

**Comment by greenlaw110** [comment]
@Elbullazul what applet is it? Can you share the link here?

**Comment by Zerophase** [comment]
@greenlaw110 It's Windows List with App Grouping. You can find it in the Applets menu, under configuration.

@Elbullazul I found the cause. It's from me adjusting the size of the panel, without letting Cinnamon scale up the size of the icons. Is there a possible workaround for this with css?

**Comment by greenlaw110** [comment]
@Zerophase Windows List with App Grouping looks perfect in the theme! thank you! BTW, I got the gap issue also, but I haven't adjusted the size of the panel, I don't even know how to adjust it. Should it be something else?

**Comment by Zerophase** [comment]
I was able to get it to resemble the pictures above, by just having the Windows logo, and letting Cinnamon scale icons on custom height panels.

**Comment by cinnamoner** [comment]
> I'm on a 1920 x 1080 screen with an aspect ratio of 16:9

@Elbullazul 
I suggest full compliance of the theme with 1080p, thus eliminating the issue described by Zerophase. Okay, I've formulated rather clumsily, but you can still extract the essence. Thank you.

**Comment by Elbullazul** [comment]
@Zerophase what's your panel size? I'll try to replicate this into my desktop to try to fix it

**Comment by Zerophase** [comment]
Let me find the property. I just set the size with the Cinnamon slider.

**Comment by Zerophase** [comment]
I have auto hide turned on, and the Panel height slider is about a mouse width away from the "P" in Panel height.  Currently, the Linux Mint forum is down. So, I can't see how to print out the value the slider has.

**Comment by Zerophase** [comment]
So, linuxmint.com was hacked last night. Might be a couple days until the site comes back up.

**Comment by Zerophase** [comment]
0.9.2 fixed the issue with the gap on the bottom of the menu. There's still a gap on the left hand side.

**Comment by Zerophase** [comment]
Sorry, for all of these posts. It sounds like the reason the theme works correctly with Linux Mint is they're on an older version of gtk. The issue might affect the theme later, but most likely whenever Cinnamon updates to a newer version, they'll have to add some padding into some of their windows.

**Comment by Elbullazul** [comment]
you're talking about https://github.com/Elbullazul/Windows-10/issues/17 @Zerophase ?

**Comment by Elbullazul** [comment]
It seems that at a certain point with small panel size Cinnamon will automatically add that small line. At least that's how it is in my system

**Comment by Zerophase** [comment]
Sorry, about posting on the wrong thread.

**Comment by cinnamoner** [comment]
@guys
LOTS OF THEMES HAVE OR HAD PROBLEMS WITH BEING BOTH MINT AND ARCH COMPLIANT. I HOPE WE FINALLY UNDERSTAND THE DIFFERENCES BETWEEN MINT AND ARCH. IF WE STILL DON'T GET IT, THE SAME OLD STORY WILL GO ON AND ON.

**Comment by cinnamoner** [comment]
@Elbullazul 
Key for action center, here:
http://icons.bav0.com/

**Comment by Elbullazul** [comment]
@cinnamoner sorry, action centre is actually embedded in Cinnamon itself. What we could do would be to build an applet for it, but none of us (i think) knows javascript, thought I'm getting started on it in college

Also, please avoid Caps on your comments. If you want to add emphasis on words add a little asterix before and after the text *so it gets like this*

thanks,

**Comment by cinnamoner** [comment]
@Elbullazul 
I understand your desire to please everyone. On the other hand, let's face it: Cinnamon, Xfce and Mate are the closest to a Windows layout.

**Comment by cinnamoner** [comment]
@Elbullazul 
At least, we now known what is needed. Javascript that is. Thanks.

**Comment by Elbullazul** [comment]
@cinnamoner my goal is that ANYONE wanting a win10 looking desktop may have access to it easily. That includes less "windowish" DEs too.

I had been to that website, but they don't have the 1511 build icons (yet?)

**Comment by cinnamoner** [comment]
@Elbullazul 
Okay. I understand your thinking.
I'll dig for the 1511 ones (maybe).

**Comment by Elbullazul** [comment]
@cinnamoner don't worry about icons. I have my own VM setup with icon grabbing software. 

since this issue appears to be linked with Arch configuration, I will close the thread. However, @Zerophase if you find a fix please share it so others who get this error can fix it too!
