### ISSUE TITLE
Scrollbars cover up ratings for Cinnamon Applets.

### ISSUE THREAD

**Issue by Zerophase** [Elbullazul/Windows-10#17]
I just noticed that the scrollbars cover the ratings for Cinnamon Applets. I don't know if there's anything we could do. Even the Cinnamon scrollbar covers them a bit. (It's much thinner though) Just thought I'd report it, in case we can do anything about it.

![workspace 1_003](https://cloud.githubusercontent.com/assets/4284284/13213195/b962e6e4-d90c-11e5-9f56-70c385f5bd34.png)

**Comment by greenlaw110** [comment]
I don't have the issue:
![image](https://cloud.githubusercontent.com/assets/216930/13216862/ab699ef6-d9b2-11e5-8144-4631eb5d5d91.png)

**Comment by Elbullazul** [comment]
@Zerophase I don't have it either. Is it still cinnamon 2.6 on Arch? Maybe it's some bug specific to Arch

**Comment by Zerophase** [comment]
@Elbullazul They're on 2.8.6 of Cinnamon.

**Comment by Elbullazul** [comment]
can't replicate the bug on Linux Mint 17.3

it seems that it's a bug that's specific to your desktop. I wish I could help but I know nothing about Arch.

**Comment by Zerophase** [comment]
I'm downloading the package, and checking if a file didn't install.

**Comment by Zerophase** [comment]
Oh, which font are you using. I'm going to check if the font selected effects this.

**Comment by Elbullazul** [comment]
the default font for cinnamon, Noto Sans 9pts

**Comment by Zerophase** [comment]
Yeah, fonts don't seem to matter. Think it's an Arch issue.

**Comment by Zerophase** [comment]
I've pushed around from a view different bug forums, and it looks like gtk issue.

**Comment by cinnamoner** [comment]
> I wish I could help but I know nothing about Arch.

@Elbullazul 
Think of Arch as something that has the latest/newest anything kinda ... Mint is more conservative but arguably more stable and less buggy.

**Comment by cinnamoner** [comment]
@Elbullazul 
From Arch, Mint, Debian, I would choose Mint. It seems to offer the best balance between new and stable.
