### ISSUE TITLE
Editable

### ISSUE THREAD

**Issue by cinnamoner** [Elbullazul/Windows-10#19]
Windows 1000 Transformation Pack. What the heck is this?

**Comment by Elbullazul** [comment]
Don't know, guess some wannabe hacker stole something from the linux mint forums associated with my username, or something else. I checked my mail and nothing has happened (yet)

As a collaborator, you have write access to the repo. Don't worry about it.

**Comment by Elbullazul** [comment]
@cinnamoner please calm down, I know your concern, but everything's under control.
Gnome-Look won't let me send you a message, says it's spam.

BTW I think I'll activate double factor security, just in case...

**Comment by cinnamoner** [comment]
@Elbullazul 
It's a big mess. I consider everything compromised. Git says I'm you.

**Comment by Elbullazul** [comment]
Screen shot plz

**Comment by Elbullazul** [comment]
I named you a collaborator. So you have administrative privileges on the repo.  If you feel you're not fit for the job I can remove you from the list

**Comment by cinnamoner** [comment]
> Screen shot plz

Coming up ...

**Comment by cinnamoner** [comment]
Here:

**Comment by cinnamoner** [comment]
I can't do it from this mobile device. Email plz. I'll attach 'em.

**Comment by Elbullazul** [comment]
just upload them here : http://imgur.com

and paste the URL that it gives you

**Comment by cinnamoner** [comment]
@Elbullazul 
I've been agonizing over the issue for so many hours. Let me have some coffee and I'll get to it.

**Comment by Elbullazul** [comment]
here is the key for you to understand what's going on : 
![capture du 2016-02-25 11 15 50](https://cloud.githubusercontent.com/assets/15310985/13325775/3f1e231a-dbb1-11e5-8148-bc0d2783273c.png)

as you can see, you & @Zerophase have admin rights over this repo, so you have access to admin rights. Get it?

**Comment by cinnamoner** [comment]
http://imgur.com/search/breach%20or%20ignorance

**Comment by cinnamoner** [comment]
@Elbullazul 
My bad. I've got it. I was concerned about the security of the repo. I used the andro-app and the link doesn't work. Also, this is not the original message. That one (about a kilometer long) crashed together with android. The only thing left in the fog is: why does Git report the v10, v1000, and Windows 1000 Transformation Pack changes having been made by you. They had been made by me. I understand that privileges come bundled with great responsibility.

**Comment by Elbullazul** [comment]
@cinnamoner my guess is that Git works like linux. Anyone who is in the sudoers group is considered as root.

**Comment by cinnamoner** [comment]
http://imgur.com/gallery/uUh8K/new

**Comment by cinnamoner** [comment]
@Elbullazul 
Just out of academic curiosity, do you think he's right or wrong?

http://www.technicalnotes.org/create-bootable-iso-from-windows-10-install-esd-file/

**Comment by Elbullazul** [comment]
don't know, never heard of ESDs before

**Comment by cinnamoner** [comment]
@Elbullazul 
Mint Software Manager is themable. I'll look for the workaround.

**Comment by cinnamoner** [comment]
@Elbullazul 
Okay. How about WIMs then? Do they sound familiar?
