### ISSUE TITLE
Theme Glitches in GTK

### ISSUE THREAD

**Issue by CanadianJeff** [Elbullazul/Windows-10#2]
QT apps are fine no issues
GTK apps have crappy looking buttons and sometimes the menus have borders around them

a possible fix would be to have something like this in gtk.css

```
.window-frame {
  box-shadow: none;
  margin: 1;
}
```

**Comment by Elbullazul** [comment]
Thanks for pointing this out. What DE do you use? Just asking...

**Comment by CanadianJeff** [comment]
XFCE with XFWM4

**Comment by Elbullazul** [comment]
I'll try your fix. Just out of curiosity, can you attach a screenshot? I'm very curious on seeing "the look" of this bug...

**Comment by Elbullazul** [comment]
Here, give it a try. I replaced previous code with yours, let's see how it does : http://b00merang.weebly.com/uploads/1/6/8/1/16813022/windows_10_tp_10081.zip

**Comment by cinnamoner** [comment]
OKAY CanadianJeff,

This issue might not affect Cinnamon but I'm eager to learn whether it has been satisfactorily dealt with. Please feedback asap. Just a "yes" would suffice and would bring some peace of mind. Thank you.

**Comment by cinnamoner** [comment]
Jeff,

I would like closure to this issue. Please tell whether it has been satisfactorily addressed or not.

**Comment by CanadianJeff** [comment]
works closing this now

**Comment by cinnamoner** [comment]
Hi CM,

Provided Jeff's fix turns out OK, how do you intend to wrap it. 0.8.1.SP1?

**Comment by cinnamoner** [comment]
OKAY. Thank you Jeff. I'm glad it works. The question remains. How do we wrap the fix, if at all? Because as is, I don't consider it a release proper. Cinnamoner out. Thank you.

**Comment by Elbullazul** [comment]
I'll see how it behaves on GNOME, cause I suspect the shadows will have disappeared. and if it's the case, I'll have to fork a specific version for Xfce

**Comment by cinnamoner** [comment]
OKAY CM. Thank you.

**Comment by Elbullazul** [comment]
Just wondering, does this fixes the buttons as well? May sound weird, but do you have murrine engine installed? I'm just wondering because I've had to fork, and this means extra work.

**Comment by Elbullazul** [comment]
No shadows on GNOME @cinnamoner . I'll have to fork for the moment
