### ISSUE TITLE
file permissions in Windows.10.Icons.v0.4.zip

### ISSUE THREAD

**Issue by tbl0605** [Elbullazul/Windows-10#20]
Hi,
that's really a minor issue, but when copying content of Windows.10.Icons.v0.4.zip to /usr/share/icons/,
I had to do a "chmod -R a+r" because some file had no global read access and could not be "rendered" by cinnamon.
For example file 256x256/apps/synaptic.png
Could you correct that in next release of your icons pack ?
Thank you very much for your hard work, your theme is really great !

Thierry.

**Comment by Elbullazul** [comment]
thanks for the warning! I thought that sudo cp fixed that problem, but I'll investigate for a better way. Thanks!

**Comment by Elbullazul** [comment]
Just wondering, this just happens with the icon pack or has Cinnamon problems rendering the theme too?

**Comment by tbl0605** [comment]
Good question @Elbullazul :) I had no problem with the Windows.10.Light.v0.9.4.zip pack because I installed it in my home directory under ~/.themes and all files had the owner read-write access rights,
BUT group&other have no rights at all (most files have -rw------- rights) so it's still not nice ;)
You can see it easily by doing:

unzip Windows.10.Light.v0.9.4.zip
find "Windows 10 Light" -ls

**Comment by cinnamoner** [comment]
@Elbullazul 
I might be wrong but the latest icon pack fails to extract correctly. And no, my interest in the theme hasn't diminished at all.

**Comment by Elbullazul** [comment]
@cinnamoner I'll see what causes the issue.  Probably a bad compression or rights as @tbl0605 points out

**Comment by cinnamoner** [comment]
@Elbullazul 
When I try to extract, prompts to overwrite. Unprecedented.

**Comment by Elbullazul** [comment]
@cinnamoner v0.9.5 is out for manual instalation only.  Plus,  you should know,  files can't be extracted if an anterior installation is already stored on disk.

**Comment by cinnamoner** [comment]
@Elbullazul 
I extracted to blank space!

**Comment by cinnamoner** [comment]
@Elbullazul 
Whenever I want to check icons inside a zip, I extract to an empty folder. There's nothing in the folder to overwrite. I just checked 0.3 and Feren's icon pack (he provides a link to his repo). It only happens with 0.4.

**Comment by cinnamoner** [comment]
@Elbullazul 
Waned to put up some screenshots earlier. It's reproducible. Check whether you can reproduce it.

**Comment by Elbullazul** [comment]
Guess your extraction tool is case-sensitive over filenames. Try unzipping in a terminal.

**Comment by cinnamoner** [comment]
@Elbullazul 
If something is unclear, please ask.

**Comment by cinnamoner** [comment]
@Elbullazul 
Plausible. I'll do that as soon as I can. GMT+2.

**Comment by cinnamoner** [comment]
@Elbullazul 
Has tbl0605's issue been sorted out?

**Comment by cinnamoner** [comment]
@Elbullazul 
Okay. I need some sleep. Cinnamoner out.

**Comment by cinnamoner** [comment]
@Elbullazul Plausible.

**Comment by feren** [comment]
Try packaging it as a deb and then it'll keep file permissions that were set to it before packaging it on every other system... (You will have to make the owner root first before packaging it like I did my skel folder for feren OS BTW)

**Comment by Elbullazul** [comment]
@feren thanks, but how do I package the deb file? do I do it manually or from the terminal or other tool?

**Comment by Elbullazul** [comment]
@feren never mind, just found how to package a deb.

I'll upload with v0.9.6 release
