### ISSUE TITLE
Cinnamon Applets

### ISSUE THREAD

**Issue by feren** [Elbullazul/Windows-10#21]
Could you possibly bundle the 'Task View' and 'Cortana' icon-ified applets with the theme or upload them somewhere because I'd like something like that on my Cinnamon and when I tried, the icons were too small on the panel... :+1:

**Comment by feren** [comment]
https://cloud.githubusercontent.com/assets/15310985/13288948/2be073f0-dadc-11e5-9585-d024c8bd52cd.png

**Comment by Elbullazul** [comment]
It's a hack I managed myself. I installed xdotool and used the "run command" applet. I also had to create a small script that simulated keypresses on alt-F1 wich activates the expo view. I COULD modify the applet but Javascript is still unknown to me.

As for "cortana" it's the same thing except it starts gnome-search-tool

if you're interested I can send you the script. Here's the applet I use : https://cinnamon-spices.linuxmint.com/applets/view/139

**Comment by feren** [comment]
Thank you...
