### ISSUE TITLE
Pure Cinnamon

### ISSUE THREAD

**Issue by cinnamoner** [Elbullazul/Windows-10#22]
@Elbullazul 
This is not really an issue but I admit having contemplated the possibility of a Cinnamon-only fork. By that I mean removing absolutely everything not necessary to Cinnamon from the bundle. Please do not take that as a form of disrespect. But I would really like a pure blood Cinnamon fork. I know we've been discussing this Cinnamon-only thing in a form or another a lot and in all likelihood you won't make a parallel Cinnamon-only fork. Now, why would I want such a fork? For one, to avoid this kind https://github.com/Elbullazul/Windows-10/issues/10 of issues. But really, there are other reasons as well amongst which me being a purist and time has come to wrap my head around the code. I haven't come into Linux to be a consumer. If that was the case I would have stayed on Windows. I want to learn about the code. It would be considerably easier for me to do so with an exclusively Cinnamon theme code. Also, I have indeed looked at the code and felt uneasy about surgically extracting Cinnamon from the bundle. All in all, I wonder whether you would have the benevolence to give me some guidance on how to achieve a Cinnamon-only thing. Please note that a delete this or that is a good start but I'd also like a complete cleanup from any residual code remaining from those other DE's. Again, this is not to be taken as an offence. Thank you.

**Comment by cinnamoner** [comment]
Okay. I've realised that this is nonsense so I'm closing it right away.

**Comment by cinnamoner** [comment]
@Elbullazul 
Have you received my e-mail?
![images](https://cloud.githubusercontent.com/assets/15638605/17415646/6179d6dc-5a93-11e6-8530-5fa1f9beae78.png)

**Comment by feren** [comment]
Dude, you have a Fork OPTION, you've used it on the icon set once before, YOU can use it again this time too... ;)

**Comment by Elbullazul** [comment]
@cinnamoner will update when i get the time
