### ISSUE TITLE
Fixed popup menu gap Cinnamon.

### ISSUE THREAD

**Issue by Zerophase** [Elbullazul/Windows-10#23]
I finally, got tired of seeing that gap, and spent some time to fix it.

Here's the code change:
```
.popup-menu{
...
border-top: 0px;
border-left: -16px;
border-right: 0px;
border-bottom: 0px;
}
```

I'm not sure if this works for all resolutions. I'm on a 1920 x 1080 display. If anyone could check with a smaller or larger display that would be greatly appreciated. I think there's a way to set it per screen resolution, but I don't work with css often enough for it.

I'll commit the change, if you think the menu looks better without a border.

**Comment by Elbullazul** [comment]
sorry for the late reply @Zerophase ,

I'll try the fix and then comment on the result.

**Comment by Elbullazul** [comment]
This fix is definetely not for all resolutions, it breaks my menu (I'm on 1366x768).

However, thanks for fixing this for your particular resolution, since now we know what to do if the problem arises in somene else's computer

**Comment by Zerophase** [comment]
I'll do some research to see if there's a general solution.
