### ISSUE TITLE
Selected buttons on Meld

### ISSUE THREAD

**Issue by rvillablanca** [Elbullazul/Windows-10#24]
Hi, I am using your Windows 10 theme, it is very nice!.

I use Meld in my daily work, and with your theme the selected buttons are not distinguished when they are selected or not.

Example for Windows 10 theme:
![windows](https://cloud.githubusercontent.com/assets/1508272/13987128/d890b0d8-f0e4-11e5-9355-4fd0a2b12795.png)

Example for Adwaita theme:
![adwaita](https://cloud.githubusercontent.com/assets/1508272/13987140/e3c65db8-f0e4-11e5-984e-940935617d1e.png)

With another Windows 10 themes the same problem occurs.

**Comment by Elbullazul** [comment]
thanks for your feedback! Let's see, that's meld in gnome-shell or unity, right?

**Comment by rvillablanca** [comment]
Hi, here is the information that you need.
![info](https://cloud.githubusercontent.com/assets/1508272/13990831/8ed6b964-f0f4-11e5-8509-557a9b848a55.png)

**Comment by Elbullazul** [comment]
fixed, a rebel piece of code prevented me from seeing the button correctly. The fix will be included in the next release (however, I do not know WHEN it will be released, I'm very busy these next weeks)

**Comment by rvillablanca** [comment]
I will be waiting for it! Thanks!
