### ISSUE TITLE
icon pack changes Deluge icon to UTorrent icon.

### ISSUE THREAD

**Issue by Zerophase** [Elbullazul/Windows-10#25]
Hey, I don't want to inconvenience you. I agree with most of the app icon changes and such. I'm just not sure if the torrent applications need to have their icons changed as well.

**Comment by Elbullazul** [comment]
well, I'll leave that to the user. You can always search and remove the undesired icons...

**Comment by Zerophase** [comment]
I don't have a problem with changing it back. I was just wondering if that's over reaching. I'm completely for changing everything to give the interface more of a Windows 10 look and feel. The torrent app icon change just feels like it might be overreaching a bit.

**Comment by Elbullazul** [comment]
@zerophase yeah,  well, I just thought it was a more windows-related icon than the regular deluge icon. ..
