### ISSUE TITLE
Support for GTK 3.20?

### ISSUE THREAD

**Issue by physicsshark** [Elbullazul/Windows-10#26]
When I updated my system it brought in GTK 3.20 which has broken compatibility with this theme, and my apps look very ugly now.  Please update this theme to have full compatibility with GTK 3.20.

**Comment by Zerophase** [comment]
Yeah, I saw that was an issue on the Arch forums. This might help. https://bbs.archlinux.org/viewtopic.php?id=211106

**Comment by physicsshark** [comment]
I don't know how to rebuild a gtk theme.  Could you explain?

**Comment by Zerophase** [comment]
I'll get started in figuring this out, once I can update to gtk 3.20. Currently, lightdm-webkit2-greeter is holding me back from upgrading. The maintainer just released a new version of the package, and just need to push it to the Arch repositories.

In the meantime Aidwata should work at least.

By the way which desktop are you running?

**Comment by physicsshark** [comment]
Adwaita works, but it really looks awful with my MATE desktop (very bad theming with MATE's panel).  Because MATE desktop is GTK2-based, it's not like everything on my desktop is ruined, but network-manager-applet, Firefox and a few other GTK3 ones have become really ugly.
Here's a screenshot from GTK3 Widget factory which will give you an idea of what's like:
![screenshot at 2016-04-09 22 51 53](https://cloud.githubusercontent.com/assets/9755486/14407840/db868e06-fea5-11e5-8e43-62d3f5b758f0.png)
All padding is completely off, and it's worth noting that there is no highlight color anywhere.  I guess the upside of GTK 3.20 is that it adds support for animations within themes (Adwaita has some nice animated checkboxes).

**Comment by Elbullazul** [comment]
Hi there, 

I would like to pre update the theme but I have no way too access gtk 3.20

**Comment by physicsshark** [comment]
You could try Arch Linux in a VM (possibly Antergos or Archbang).  I think Fedora 24 has gtk 3.20, so you could try a pre-release of that.
I hope this (https://feaneron.com/2016/01/04/quick-guide-to-port-an-app-for-gtk-3-20/) and this (https://blogs.gnome.org/mclasen/2015/11/20/a-gtk-update/) helps.  Note that gtk 3.20 is supposed to have a stable theming api, so you wouldn't have to keep updating with the new gtk versions.  
Also, as described in the comments of the second article, it's possible to ship both gtk 3.18 and gtk 3.20 themes for backwards compatibility.

**Comment by cinnamoner** [comment]
Hi guys,

From what I recall petrucci4prez's daily driver is Arch. I always reference the guy when it comes to the gtk stuff. He seems to have dealt with the issue nicely.

**Comment by Zerophase** [comment]
I'm going to try changing css class and id names based off of this. https://github.com/City-busz/budgie-desktop/commit/847261bdbe7e6f666885e6e433c7b9e8aa79aecc

**Comment by kozross** [comment]
I too am having issues, particularly of menu 'crowding'. I have attached a screenshot showing an example of what I mean - the menu in the top-left corner is way too tightly-packed. It shows up in several other GTK3-using apps too (notably Evince, in which it is even worse).
![screenshot_2016-04-12_21-04-54](https://cloud.githubusercontent.com/assets/8463904/14455186/57bcb420-00f2-11e6-8a07-5f6e4f63032b.png)

**Comment by Elbullazul** [comment]
ok guys, just found the actual adwaita 3.20 source code : https://git.gnome.org/browse/gtk+/tree/gtk/theme/Adwaita/gtk-contained.css

just if you want to help or try fixes by yourself while I try to install fedora 24 alpha (fingers crossed...)

**Comment by Zerophase** [comment]
I'll play around with it when I get the chance in a few days.

**Comment by Elbullazul** [comment]
I've been adding code, this is how it looks now : 

![raspbian](https://cloud.githubusercontent.com/assets/15310985/14692824/ee34fec2-0727-11e6-82e8-ae1ffa54f7b4.png)

what's been fixed : 
- menu padding
- menubar & header bars padding
- sidebar

**Comment by Elbullazul** [comment]
all right, just had a general lookup of the new code, it's horrible! it's just a bunch of definition for "gnome-oriented controls and elements"

I personally prefer how the GTK 3.14 themes were made, with simple code and classes

**Comment by Zerophase** [comment]
I'm looking at the changes in gtk-contained through diff right now. I think it would be easier to maintain, if we moved to generating the css with sass. 5,000 line file isn't the nicest thing to browse through for changes.

**Comment by Elbullazul** [comment]
you mean scss @Zerophase ?

I don't know, could be...

**Comment by Zerophase** [comment]
Yeah, it's basically the same thing. Got the checkbutton working. Ok, it's a lot easier to fix than I thought at first. Still really annoying that they don't have documentation on changes. Even just something auto generated.

**Comment by Elbullazul** [comment]
@Zerophase saw you had the checkboxes working?

I "fixed" window frames, buttons (kind of) and menubars

**Comment by Zerophase** [comment]
@Elbullazul I thought I had fixed the check boxes, but turns out I was just mistaken.

**Comment by Elbullazul** [comment]
Basic support for Gnome 3.20 here : https://github.com/Elbullazul/Windows-10/releases/tag/v0.9.7-alpha

**Comment by Zerophase** [comment]
I'll see if I can figure out how to get radio and check boxes displaying correctly. This should help me a lot. I think I'm almost there.
