### ISSUE TITLE
Very pale scrollbar

### ISSUE THREAD

**Issue by kozross** [Elbullazul/Windows-10#27]
![I've attached a screenshot to show what I mean. ](https://cloud.githubusercontent.com/assets/8463904/14763862/76a71336-09f7-11e6-8f5f-de41c98d256e.png) 

I find it quite jarring from the rest of the theme, and the thumb is too hard to distinguish unless clicked.

**Comment by Elbullazul** [comment]
originally it looked like this : 
![windows 10 v0 5 1 6](https://cloud.githubusercontent.com/assets/15310985/14765051/962015c8-099d-11e6-984d-333b9960cd96.png)

but then I somewhere found a picture showing that the beta build of win10's dark theme didn't change the scrollbar color

I agree with you that it looks out of place, and I think I'm gonna change it in the next release

thanks for your feedback!

**Comment by Elbullazul** [comment]
So, v0.9.7 Stable will bring darker scrollbars, as illustrated below : 

![capture du 2016-05-25 09 54 37](https://cloud.githubusercontent.com/assets/15310985/15542423/b5ed918a-225e-11e6-9e82-ede2746175c2.png)
