### ISSUE TITLE
Crowding in file chooser

### ISSUE THREAD

**Issue by kozross** [Elbullazul/Windows-10#28]
![Screenshot to show what I mean](https://cloud.githubusercontent.com/assets/8463904/14763948/7cbb38e4-09fa-11e6-932e-30c02f9156b9.png) Note the crowding at the top of the file chooser where the file path is displayed - the directory names run into each other, and look like one big directory name instead of several separate ones.

**Comment by Elbullazul** [comment]
is this gnome 3.20?

**Comment by kozross** [comment]
I'm using Xfce 4.12. This file chooser, however, comes from Evince 3.20, which I assume is from GNOME 3.20 as well.

**Comment by Elbullazul** [comment]
all right, this will be fixed with next release for gnome 3.20

**Comment by Elbullazul** [comment]
try out this : https://github.com/Elbullazul/Windows-10/releases/tag/v0.9.7-alpha
