### ISSUE TITLE
Cinnamon menu issues after installing pre-release.

### ISSUE THREAD

**Issue by Zerophase** [Elbullazul/Windows-10#29]
These are some of the issues I've noticed with Cinnamon. I have the latest pre-release installed. Do you have the same issues?

The blue on some of the windows is from the screen capture tool.

![gtk-theme-windows10-git_002](https://cloud.githubusercontent.com/assets/4284284/15060234/1f3eabc2-12ee-11e6-8f5a-bff49b044df6.png)
![system settings_001](https://cloud.githubusercontent.com/assets/4284284/15060235/20bdf656-12ee-11e6-8ccb-db09d6c08ce7.png)
![effects_003](https://cloud.githubusercontent.com/assets/4284284/15060236/22999278-12ee-11e6-9e0b-de1bf367e9d3.png)
![authenticate_004](https://cloud.githubusercontent.com/assets/4284284/15060238/27afac48-12ee-11e6-8a9c-82e591d2f007.png)

**Comment by Elbullazul** [comment]
Well I don't know for the floating icons.  It looks more like a software bug or something like that. 

Weird that the entry doesn't have borders. 

As for the buttons I'll have a look at the code again 

Thanks for the feedback

**Comment by Zerophase** [comment]
It looks like the beta might have fixed all of the Cinnamon issues. I just don't see selections in Cinnamon for Window borders, and Desktop from this release.

I'm currently using the Arc Dark theme, and noticed they don't have a separate folder for Cinnamon. Could all of the new api standardized theming across different desktops?

**Comment by Elbullazul** [comment]
I don't know.  On their github page they still have a cinnamon folder 

https://github.com/horst3180/arc-theme/tree/master/common

As for the Window borders it's because there is no metacity theme (didn't include it) 

As for the selection,  I have my idea what could be the cause

**Comment by Zerophase** [comment]
I must have mised arc up with another theme. I do have other themes that seem to be working fine without the cinnamon folder. I'm guessing you just can't individually stylize Cinnamon specific windows without it.
