### ISSUE TITLE
Computer Bookmark icon very big

### ISSUE THREAD

**Issue by fatihusta** [Elbullazul/Windows-10#30]
OS: Ubuntu 16.04 - Unity 7

![verybigicon](https://cloud.githubusercontent.com/assets/11256228/15288956/6221661e-1b77-11e6-88da-cc923870b8c8.png)

I changed with computer icon
```
sudo cp /usr/share/icons/Windows 10 Icons/scalable/devices/drive-harddisk-symbolic.png /usr/share/icons/Windows 10 Icons/scalable/devices/drive-harddisk-symbolic1.png
sudo cp /usr/share/icons/Windows 10 Icons/16x16/devices/computer.png  /usr/share/icons/Windows 10 Icons/scalable/devices/drive-harddisk-symbolic.png
```

And ReApply icons options

Finally
![screenshot from 2016-05-16 15-45-37](https://cloud.githubusercontent.com/assets/11256228/15289810/42aaec28-1b7d-11e6-93aa-cce6c8db458f.png)

**Comment by Elbullazul** [comment]
I'll take care of that, I (badly) supposed that icon wasn't used anywhere else than on dark surfaces. I'll be changing it for the next icon pack

**Comment by Elbullazul** [comment]
It's fixed, next release will bring the change

**Comment by fatihusta** [comment]
thanks.
