### ISSUE TITLE
Cinnamon toggle buttons not working.

### ISSUE THREAD

**Issue by Zerophase** [Elbullazul/Windows-10#33]
0.9.7 fixes most of the Cinnamon issues. I just noticed that the toggle buttons aren't getting themed. In the pre-release they were receiving a theme fine.

![themes_001](https://cloud.githubusercontent.com/assets/4284284/15559998/c3644720-22ac-11e6-815b-addf2ccd69fa.png)

**Comment by Elbullazul** [comment]
can you post a screenshot of the issue please?

**Comment by Elbullazul** [comment]
But v0. 9.7 isn't for gnome 3.20,  I'm not even sure we can blend the code with other releases for gnome 3.18 or earlier... 

I'll have to fork a version for gnome 3.20 it seems...

**Comment by Elbullazul** [comment]
just wondering, does this version has any issues with menubars?

**Comment by Zerophase** [comment]
It doesn't as far as I noticed. But, there is a weird border when scrolling through windows.  That black border shows up with the window contents sliding down it.

**Comment by Elbullazul** [comment]
does it happen on the beta too?

**Comment by Zerophase** [comment]
No it doesn't happen on the beta. 

Actually, the Windows 10 theme seems to be broken again on Cinnamon. (worse than before) There were updates to Cinnamon since this was released.  Let me try reinstalling it.

**Comment by Elbullazul** [comment]
try doing this : replace the gtk-3.0 folder from version 0.9.7 with the gtk-3.0 folder from the beta release

you should then have a nice theming with GTK apps and no problem getting the latest cinnamon theme
