### ISSUE TITLE
Support gtk-3.20

### ISSUE THREAD

**Issue by jristz** [Elbullazul/Windows-10#35]
This is more a future thing since ubuntu 16.10 (if I remmember correctly) and any future mint based on that will be based on gtk 3.20.

Gtk 3.20 revamp the theming HEAVILY that now is just css, this make gtk3.18 and lower completely incompatible with gtk 3.20 breaking sky and earth, so far mate-themes from git and arc-theme from git and numix-themes from latest git are compatible (if you want based on them) to take a look and see that going to be done (or not done)

so the issue resume in add support for gtk 3.20.

**Comment by Elbullazul** [comment]
@jristz thank you for you attention on this subject. I will have a look at the Numix theme (I had no idea it was ready). In the meantime, we have a beta version (very basic support) for gnome, if you want to give it a try

**Comment by jristz** [comment]
yeah, I'm using arch and they already have gtk 3.20 so any beta pointing to fix that I will be able to test natively

**Comment by Elbullazul** [comment]
https://github.com/Elbullazul/Windows-10/releases/tag/v0.9.7-beta

give it a try. According to our collaborator @Zerophase it works well. All that's left are some rgba colors to redefine

**Comment by cinnamoner** [comment]
Gtk issues always drive me nuts. The themes will adapt.

**Comment by 15w34r0n3D4y** [comment]
Thank you for theme! 

I have question how fix this border? Thank you for answer.

![how-fix-it-win10-gnome-themes-terminal](https://cloud.githubusercontent.com/assets/13278733/15990071/c6cb7ace-3089-11e6-9134-2dcd978d93f3.png)

**Comment by Elbullazul** [comment]
Ooooh,  I'll have a look at this first.  What terminal is that?

**Comment by 15w34r0n3D4y** [comment]
It's GNOME Terminal 3.20.2 :)

**Comment by Elbullazul** [comment]
@15w34r0n3D4y try this : open the gtk-contained.css file and search for 
> decoration {

then, replace box-shadow: 0 3px etc... with
> box-shadow: none;

same for
> decoration:backdrop 

(inactive)

see how that turns out

**Comment by 15w34r0n3D4y** [comment]
It works, thank you! :+1:

**Comment by Elbullazul** [comment]
glad it works!
