### ISSUE TITLE
Selected Item Not showing Progress 

### ISSUE THREAD

**Issue by fatihusta** [Elbullazul/Windows-10#36]
I'am downloading some files with transmission.
I can't see selected item progress

![transmission_001](https://cloud.githubusercontent.com/assets/11256228/15957819/410675fa-2efa-11e6-9ecb-d232c59cba3e.png)
![transmission_002](https://cloud.githubusercontent.com/assets/11256228/15957820/410b4a26-2efa-11e6-9043-4c6fe0a3bafa.png)

**Comment by Elbullazul** [comment]
That's gnome 3.18 right?

**Comment by fatihusta** [comment]
Ubuntu 16.04 Unity7

**Comment by Elbullazul** [comment]
Ok,  I'll see how to fix this.

**Comment by Elbullazul** [comment]
found a solution. still having to implement it in dark theme and repack and we're ready to go

**Comment by Elbullazul** [comment]
@fatihusta by the way, that one rectangle you added it yourself, right?

**Comment by fatihusta** [comment]
yes, I added white area for hide torrent name.

**Comment by Elbullazul** [comment]
V0. 9.8 fixes this
