### ISSUE TITLE
Please make font color in dark theme not so white

### ISSUE THREAD

**Issue by greenlaw110** [Elbullazul/Windows-10#37]
The font color in dark theme looks too light. 

The following snapshot is the effect I've manually changed `#fff` to `#eee`. See the font in the menu bar, it's still whiter than the font color in my sublime text theme:

![image](https://cloud.githubusercontent.com/assets/216930/15984310/78cbe0e6-3009-11e6-902b-75a0b27fe8e3.png)

**Comment by Elbullazul** [comment]
What color would do, according to you?
