### ISSUE TITLE
Cinnamon Dark Theme bug

### ISSUE THREAD

**Issue by 15w34r0n3D4y** [Elbullazul/Windows-10#38]
How can I fix it? Thank you!

![cinnamon-bug-win10-t](https://cloud.githubusercontent.com/assets/13278733/16100685/5711111a-3360-11e6-8d33-1ff62d96afe3.png)

Nemo 3.0.3
Files 3.20.1

**Comment by Elbullazul** [comment]
Use the beta version from here : https://github.com/Elbullazul/Windows-10/releases/tag/v0.9.7-beta

unfortunately,  we aren't ready to create a dark variant yet,  but if you ask,  I can provide a temporary solution

**Comment by 15w34r0n3D4y** [comment]
I try beta version but it's only light theme I love dark theme can you tell me a temporary solution, please :hand:

**Comment by Elbullazul** [comment]
ok, here's what we'll do : download the beta release while I write a quick gtk.css file to change the colors.

deal?

**Comment by 15w34r0n3D4y** [comment]
Ok, thank you again.

**Comment by Elbullazul** [comment]
@15w34r0n3D4y ok, here is the corrected dark file (haven't time to test it, you tell me if it's ok) : 

open the gtk.css file in Windows 10 Beta/gtk-3.0 and replace ALL code with the following : http://pastebin.com/iJJL6VcM

Please post a screenshot of the resulting theme, I'm curious how it will look :D

**Comment by Elbullazul** [comment]
@15w34r0n3D4y sorry to insist, but have you tried the patch?

**Comment by 15w34r0n3D4y** [comment]
Download beta source and put gtk.css on gtk-3.0 in Dark Theme folder here is screenshot ....

![win-theme-cinnamon-2](https://cloud.githubusercontent.com/assets/13278733/16103924/0009a810-337d-11e6-9bee-01605933bef5.png)

**Comment by Elbullazul** [comment]
Mmm, 

I think there's a misunderstanding here. 

Have you installed the beta release?

**Comment by Elbullazul** [comment]
This fix only works for the original beta code

**Comment by 15w34r0n3D4y** [comment]
Original you mean Light beta? And then put in new css file?

**Comment by Elbullazul** [comment]
@15w34r0n3D4y il have to test that.  I'll be back in an hour or so

**Comment by Elbullazul** [comment]
had to correct some colors, so I did a complete dark variant at the same time. here's the file
[Windows 10 Dark.zip](https://github.com/Elbullazul/Windows-10/files/318531/Windows.10.Dark.zip)

**Comment by 15w34r0n3D4y** [comment]
Thank you again. 

Btw on GTK 3.14.5-1 and Files 3.14.1 not show windows button (see screenshot), Nemo 2.2.4 showing fine. 

![gtk-3 14-files](https://cloud.githubusercontent.com/assets/13278733/16140877/b4400c74-3455-11e6-8417-8e27a18b8f91.png)

One more question, which menu you use like on your screenshot is this Dexi Menu?
Screenshot: https://cloud.githubusercontent.com/assets/15310985/16102805/2d76a816-3341-11e6-8a4b-67e8253851c7.png

**Comment by Elbullazul** [comment]
@15w34r0n3D4y the menu is the Slingshot launcher : https://github.com/jfarthing84/cinnamon-slingshot

I think GTK 3.14 and lower used Metacity for window decoration. I don't know how to change those except maybe with dconf or gconf

**Comment by 15w34r0n3D4y** [comment]
I try with gnome tweak tool but no effect. :/

**Comment by Elbullazul** [comment]
@15w34r0n3D4y I just found this, maybe it will work (hope it does)

Run in terminal:
>  gsettings set org.gnome.desktop.wm.preferences theme "$theme"

**Comment by 15w34r0n3D4y** [comment]
@Elbullazul nope, not working. :/

**Comment by Elbullazul** [comment]
I don't know then.  3.14 apps were made to run with metacity themes,  but 3.20 is supposed to redirect those system calls to ssd decorations.  

I'll search a bit more,  but I don't think there's a way to change the metacity theme from 3.20 to 3.14

**Comment by 15w34r0n3D4y** [comment]
Ok, thank you anyway. :)
