### ISSUE TITLE
File manager (nautilus) under gtk 3.20 has white color shadow. 

### ISSUE THREAD

**Issue by Thisuu** [Elbullazul/Windows-10#39]
As i noticed, Light theme is having a white color shadow for some apps like nautilus. There were also few bugs in gnome shell theme and i resolved them myself. Anyway,it's a great theme!

**Comment by Elbullazul** [comment]
@Thisuu can you post your fixes for Shell please? I rarely get to use that platform, so any help is very much appreciated.

the shadow color I'm trying to find the cause, it's really weird. On fedora 24 I don't have that, I'll give it a try on manjaro 16.06
