### ISSUE TITLE
Issue with new version of libcroco

### ISSUE THREAD

**Issue by Zerophase** [Elbullazul/Windows-10#4]
I ran into this issue with the Windows 10 theme in Cinnamon. It could potentially effect all the desktops based on Gnome.

Here's more on the issue: https://bugs.archlinux.org/task/47367

Sounds like something might have changed with how libcroco parses css.

**Comment by cinnamoner** [comment]
OKAY, thank you Zerophase. I'm sure CM will address the problem.

**Comment by cinnamoner** [comment]
Hi CM,

Maybe you should freeze it feature wise until those are dealt with (counted 3 bug reports so far). Introducing new features is a good thing but they tend to bring about bugs. Almost certainly a feature upgrade release is always buggy. That's normal. It's just the way it is. But proceed as you see fit.
Thank you.

**Comment by Elbullazul** [comment]
Hi @Zerophase , could you develop a bit more? I don't understand what Libcroco is. I understand upgrading hangs Cinnamon, but is that only with the Win theme?

**Comment by cinnamoner** [comment]
Following with great interest.

**Comment by Zerophase** [comment]
Libcroco is the css theme parsing engine.  It looks like the newest version uses .scss, in place of .css

**Comment by Elbullazul** [comment]
Is the windows 10 theme the only one that crashes your computer?

**Comment by Zerophase** [comment]
I think it's just Windows 10. The Mac theme would probably do it too. This is what's going on with the document format. http://stackoverflow.com/questions/5654447/whats-the-difference-between-scss-and-sass

I'm trying to figure out exactly which files need to change to get the theme working with newer versions of libcroco. I believe it just needs `.css` changed to `.scss`

**Comment by Elbullazul** [comment]
Ok, can you report wich files need change? Also, is this just for arch that libcroco gets updated or everywhere else too?

**Comment by Zerophase** [comment]
I can get you a list of files. Just let me play around with the theme on the newer libcroco. I think as of right now Arch is the only platform that uses the newest release of Libcroco. (Usually, they update packages first) But, it should be coming out on the other platforms within a few months.

**Comment by cinnamoner** [comment]
Can you wrap your head around scss CM? Clearly has some advantages but might not be piece of cake.

**Comment by Zerophase** [comment]
It's basically, the same as `css` the only difference is you can embed `css` classes within each other.

**Comment by cinnamoner** [comment]
It might be the future (scss) and it's more efficient but do you master it well enough at this moment in time?

**Comment by Elbullazul** [comment]
are you kidding? I just learned SCSS existed.
But if it's CSS with something else, then there's no problem.

**Comment by Zerophase** [comment]
You might need to maintain two files till `0.6.10` replaces `0.6.9'

**Comment by cinnamoner** [comment]
Sooner or later transition to scss should happen. Better sooner. I would take Zerophase's advice.

**Comment by cinnamoner** [comment]
OKAY. I think you should first document about what scss is all about. There is an xp theme done with scss. Trying to provide a link just to point out an example.

**Comment by cinnamoner** [comment]
"SCSS is really powerful and allows one to express CSS in a more compact format...pretty sure Adwaita itself has ~10000 lines of CSS (both light and dark) but this requires <5000 lines of SCSS. I personally think it's better organized as well, for instance something like this in CSS:

a {
color: white;
}

a:hover {
color: black;
}

a b {
color: green;
}

can be written in SCSS as:

a {
color: white;
&:hover { color: black; }
b { color: green; }
}

There's also nice things like loops and if/then logic that can be used to further simplify things.

If you want to learn, the guide I used for all this was http://sass-lang.com/guide. My advice would be to start playing with the original Adwaita SCSS (it's cleaner than mine) and see how any changes you make will affect the output (gtk-contained.css and gtk-contained-dark.scss)"

That is an excerpt from CinnXP theme conversation. You can find said theme on Look and/or Git.

**Comment by cinnamoner** [comment]
I don't know whether this helps or not but I have tried.

**Comment by cinnamoner** [comment]
All credit for the conversation the excerpt is part of goes to Bluedxca93 and Petrucci4prez.

**Comment by cinnamoner** [comment]
So, what do you think CM?

**Comment by cinnamoner** [comment]
Answer pending ... I'll be back at a later time.

**Comment by Elbullazul** [comment]
Even if Adwita was coded in SCSS, my laptop has Mint 17.3 with the old libcroc package. I can't edit SCSS 'cause there's no way to render it in Mint.
I'll wait @Zerophase 's report and then probably fork a new version

**Comment by cinnamoner** [comment]
I just wonder if old and new cannot be made to coexist. I don't want to push the envelope but consider your theme working with old as well as new Libcroco without forking (think hybrid). If that is not technically feasible then, of course, a fork. That means 2 branched development though. At any rate, I would like the theme to be future proof. My formulation might not be the best but I think you can still extract the essence. I'm not on Arch me but Mint 17.3 so the whole Libcroco issue is of little relevance for me personally at this moment in time. Nonetheless, I think ahead to 16.04 LTS (probably late spring) and all novelties associated. If you can hold out (at least) until then, we can safely assume that you'll have been made history.

**Comment by Elbullazul** [comment]
I'll see if actual GTK supports SCSS...

**Comment by Elbullazul** [comment]
No support, at least of Cinnamon themes

**Comment by cinnamoner** [comment]
In a nutshell, the 3 bug reports (might be wrong but counted that many) have no tangency with Mint Cinnamon 17.3 at all, right?

**Comment by cinnamoner** [comment]
I might be egotistical but all I am interested in is Cinnamon having a bright future with your theme. Everyone is free to stand up for his or her favorite DE so if any of you have other preferences that's fine with me. Also, I've taken note of the GTK stuff. Thank you guys. It's been a fine day.

**Comment by Elbullazul** [comment]
3 bugs? I just see one who is related to code issues...

None of this stuff affects 17.3 for the moment...

**Comment by Zerophase** [comment]
Alright, so I haven't heard back from anyone on Arch. I guess I could I could write a script that just just changes the file extension to `.scss` for Arch.  Also checking in at the Linux Mint forums to see if .scss files can be parsed in their distribution. It's probably an update you won't need to make for at least a few months.

**Comment by cinnamoner** [comment]
OKAY. Sooner or later scss or the lack of it in the theme might pose problems on all platforms. It just so happens that Arch seems to introduce new things first.
As for the bugs, I'll try to set the record straight:
1. Libcroco issue by Zerophase (not a bug but incompatibility with new version)
2. The GiulioMartena calendar issue in G Shell (not a bug but visual inconvenience)
3. The CanadianJeff issue (XFCE) which has already been addressed in a way or another (not reflected in the release structure)
Therefore, I apologize for the erroneous formulation. All responsibility taken.

**Comment by cinnamoner** [comment]
Also, I am no expert on Linux. Just trying to apply common sense. Seemingly with mixed results.

**Comment by cinnamoner** [comment]
At present, I would issue a new release or service pack encompassing the fix for the CanadianJeff issue and what Zerophase suggested, namely two files till 0.6.10 phases out 0.6.9 entirely. And, of course, anything you see fit. Thank you for putting up with me.

**Comment by cinnamoner** [comment]
Last but not least (might be on the wrong thread), I would consider implementing Zerophase's suggestion (2 files) in W7 as well.
My interventions should not be interpreted as a "do this, do that" and let me be excused for my bird eye view on a great many aspects. Thank you. Cinnamoner out.

**Comment by Elbullazul** [comment]
I'm not shure on the scss, since I can't try out and verify compatibility. @Zerophase , do all the .css files need to be converted to .scss? 

@cinnamoner I appreciate your enthusiasm but I'm kind of blurred, not seeing the issue or having precise info yet.

**Comment by Elbullazul** [comment]
@cinnamoner as for the calendar stuff I'll have a look at it right now

**Comment by cinnamoner** [comment]
Enthusiasm yes. You can say that again. I'm thinking about the theme day in and out. As for the momentary blur, it's just that. I am sure you can sort things out, eventually.

**Comment by cinnamoner** [comment]
Undoubtedly, Zerophase is the core player on this thread. But if any of you reading this have relevant insight, please don't hesitate and join!

**Comment by Zerophase** [comment]
So, I got it working with the latest version libcroco by renaming all `.css` files for the theme to `.scss`, but I just get the default Cinnamon desktop now. At least I can get into the desktop. I'll have to dig around some more to see which files should be which format.

**Comment by Zerophase** [comment]
Looks like the only file that needs to be changed to get the desktop to boot up is `cinnamon.css`, but still the taskbars fallback to the default cinnamon colors, and I don't believe nemo looks quite right.

Nemo:
![homeimage](https://cloud.githubusercontent.com/assets/4284284/11834850/a37a789e-a395-11e5-8e80-682231abe872.png)

Tasbar:
![taskbar](https://cloud.githubusercontent.com/assets/4284284/11834877/da88bf8a-a395-11e5-8b0d-d961c77211a7.png)

**Comment by Elbullazul** [comment]
great! I think maybe you'll have to rename the files in these folders too : 
*- third-party-APPLET-stylesheets *
*- third-party-DESKLET-stylesheets *
*- third-party-EXTENSION-stylesheets  *

Those are CSS files as well, maybe that's why Cinnamon doesn't read the main file as it should?

also, GTK themes work fine without the scss conversion?

**Comment by Elbullazul** [comment]
I think nemo looks as it should : 

http://b00merang.weebly.com/uploads/1/6/8/1/16813022/3900807_orig.png

**Comment by Zerophase** [comment]
Well, I renamed everything to use `scss`, and edited `cinnamon.scss` to reflect the changes. Everything looks correctly now, except for the taskbars. (same as it was before) I don't know what else I need to add to `cinnamon.scss`.

**Comment by cinnamoner** [comment]
Following with great interest.

**Comment by cinnamoner** [comment]
Experimental approach might not work or not produce desired results that quickly. I think of external reference. But it needs to be tracked down.

**Comment by Zerophase** [comment]
I can't really find much documentation on libcroco.

**Comment by cinnamoner** [comment]
OKAY. I'll try to bring in more people. Linux is all about helping each other out, right?

**Comment by cinnamoner** [comment]
OKAY. I've changed my mind. Linux is not just about helping each other out. Coming from Look. I wonder how little brains is little enough to vote a theme down.

**Comment by Zerophase** [comment]
Looks like it might be an issue with libcroco, once again.  This is going to take a few days to figure out. https://bbs.archlinux.org/viewtopic.php?id=206287

**Comment by cinnamoner** [comment]
@Elbullazul,

You are mature enough to realize that those votes (up or down) don't count for anything. The sole problem with democracy is that it allows idiots to cast a vote. If I were you, I would disengage from Look altogether. I just wonder what motivates you. There are much more meaningful ways to get motivation from. As for value, I almost always find it where least advertised. There are times when one can't even log in to Makulu's because the site is under siege. Why? Probably because Raymer realeased a distro called Aero. On the other thread I've seen some guy rightfully asking for a ppa. The higher you will grow the more exposed you will become to idiots. One can't even blame those guys because they were born that way and their chance to improve is slim at best. As for the issue at hand (.scss), it will work out when least expected.

**Comment by cinnamoner** [comment]
@Zerophase 
"Looks like it might be an issue with libcroco, once again. This is going to take a few days to figure out."
It doesn't matter Zerophase; where there's a will there's a way. We'll wait it out. We as in "us who know what value is".

@Elbullazul 
Please feel free to delete my previous comment. You'll prevail becasuse you have it in you. Idiots pushing value down have to be ignored.

**Comment by Elbullazul** [comment]
@cinnamoner thanks for those words of enthusiasm. I just keep on Look because it's the platform for "main linux themes" and while the theme won't be very known I'll let the theme over there. Maybe after too, but just providing a link to here, who knows? 

I'm a bit worried about negatives because Look automatically deletes themes with low average voting, that's it

**Comment by Elbullazul** [comment]
@Zerophase well, I hope you can rebuild soon. Sorry for the troubles caused.

**Comment by cinnamoner** [comment]
@Elbullazul 
Got it. On the other hand though, I'm just one guy me and as such can't vote twice. But if you want an army of upvoters to overwhelm everything in their way, that I can set up. Joking of course and I know you see my point. I'm considering to delete my latest comments now that they've got stored.

**Comment by cinnamoner** [comment]
@Elbullazul 
From now on I'll try to stick to the issue at hand.
@Zerophase 
Sorry for hijacking your thread. I apologize for the annoyance.

**Comment by cinnamoner** [comment]
"so I think I get the gist of the thread, but just to clarify...you guys know that the gtk3 theme parser doesnt actually read the scss files right?" The quotation comes from Petrucci4prez.

**Comment by cinnamoner** [comment]
@Elbullazul 
Just felt the need to reedit some comments. Just not worth it.

**Comment by Zerophase** [comment]
With the newest version of libcroco released today the css files once again work.

**Comment by Elbullazul** [comment]
Great! so it was just a problem with libcroco ?

**Comment by Zerophase** [comment]
Yeah.
