### ISSUE TITLE
Checksums

### ISSUE THREAD

**Issue by cinnamoner** [Elbullazul/Windows-10#41]
@Elbullazul 
I now it was me to suggest them, but SHA512 is overkill. MD5 or SHA1 would suffice.

**Comment by Elbullazul** [comment]
@cinnamoner I prefer sha512. I don't know how MD5 works, but with SHA512 it's less likely to get a duplicate.

anyhow, I prefer 512 because that's with what I started.

but if you want to I can include MD5 too

**Comment by cinnamoner** [comment]
>with SHA512 it's less likely to get a duplicate.


@Elbullazul 
You bet. Like once in a trillion. Multiple checksums would be a headache. Okay, then keep the SHA512 but put the name of the algorithm in front of the string, like: SHA512: .....
There's also SHA256 which would be good enough but it's up to you.

**Comment by Zerophase** [comment]
Personally, I just download the packages and check what the SHA1 sum is.

**Comment by Elbullazul** [comment]
@Zerophase does arch require checksums before installing the package

**Comment by Zerophase** [comment]
It doesn't require them. Usually, it's recommended to check that the package downloaded correctly. So, a sha1 sum does the job.

**Comment by cinnamoner** [comment]
@Elbullazul 
Whenever you download and a checksum is posted, make sure you use the double-blind method. Me paranoid? No Sir. The father of Linux checksums the checksums.

**Comment by cinnamoner** [comment]
@Elbullazul 
Virustotal doesn't go any higher then SHA256.

**Comment by cinnamoner** [comment]
Again, checksumming is performed:
1) To make sure the package hasn't accidentally corrupted.
2) To make sure the package hasn't been tempered with by a third party (possibly with malicious intent).

**Comment by cinnamoner** [comment]
@Elbullazul 
And one more, very important, about cheksumming: make sure it doesn't turn into compulsion.

**Comment by cinnamoner** [comment]
@Elbullazul 
What do you mean by duplicate? What are the odds for someone the create a clone of your zip?  Not even you can create two identical zips unless by copy-paste.
Perhaps you've refered to a collision. That's a rare event. Like really rare.
