### ISSUE TITLE
On-topic Discussion About Budgie Desktop Environment 

### ISSUE THREAD

**Issue by cinnamoner** [Elbullazul/Windows-10#42]
_Welcome to Budgie Desktop Environment Discussion Thread_
_Let's practice order and logic!_

**Comment by cinnamoner** [comment]
@Elbullazul 

https://m.youtube.com/watch?v=LYvX4hDFXKg

https://m.youtube.com/watch?v=RfDyfHKRmz0

I'm not posting 'em 'cause I'be got nothing better to do. Please watch n listen with some attention.
Thank you.

**Comment by cinnamoner** [comment]
@Elbullazul 
Okay. I realize I might have been a bit rough around the edges in expression. That wasn't my intention though. It's just that I'm looking at this beta 18 n I'm frustrated with it. I really hope they'll improve 'cause this is what the name says. A beta.
As far as Stark is concerned, I really think it's the best menu for Cinnamon. They should make it default for Cinnamon. Or if they don't want it that way, at least they should make their very own home fork n update it with every new version of Cinnamon.
Don't get me wrong. Cinnamon remains my favourite DE. It's just that I don't see the point in updating it so often for so little benfit (to say the least).
As for Budgie, It seems something between Cinnamon n Shell n more. It kinda feels good to have an alternative to Cinnamon that I also like. Yeah. The more I look to it, the more it grows on me. N the Budgie Remix is a neat little distro. All you need out of the box. N it's not like it's not decently themed up, but one extra theme would be nice. Obviously, I'm talking 'bout the key theme of your lineup. It's up to you now. Thanks for reading through.

**Comment by cinnamoner** [comment]
@Elbullazul 
You know what? Let's put it in the standby ideas category. It's a hybrid desktop. And you've got so much going on already. I'm not deleting it, just shutting it down.

**Comment by cinnamoner** [comment]
@Elbullazul 
Preferably, a Budgie only fork. Not bundled. I'm looking forward to hear from you n learn your insights.

**Comment by cinnamoner** [comment]
@Elbullazul 
Yeah / Nay?
Please say a short word about what you're cooking right now and about your roadmap. Thanks.

**Comment by cinnamoner** [comment]
@Elbullazul 
If you're having fun, that's good. If something has made you unhappy, reject it at once. Nobody will get upset about it.

**Comment by Elbullazul** [comment]
@cinnamoner budgie is a fork of gnome-shell, so the actual theme should support it

still some fixes needed thought.

**Comment by cinnamoner** [comment]
@Elbullazul 
Cool!

**Comment by cinnamoner** [comment]
@Elbullazul 
¡Enhorabuena por el bebé nuevo! (0.9.9)

**Comment by Elbullazul** [comment]
@cinnamoner from what i understand budgie works almost the same way as the regular gnome de with some features added/removed

current TP (0.9.9) supports gnome 3.18, and unless budgie only works with gtk 3.20 it is currently supported

I think I should add 'and derivatives' on the list of supported DEs

**Comment by cinnamoner** [comment]
@Elbullazul 
Inasmuch as what's the difference between a derivative and a fork there's no clear definition. Yes, include  Budgie as well, please. I don't mind the bulk approach as long there aren't any conflicts between different  DEs codewise.

**Comment by cinnamoner** [comment]
> 'and derivatives'

@Elbullazul 
If Solus defines it that way, then it's okay. If not, refer to it as 'Budgie'. If you say 'and derivatives' Budgie' users might not realize it's for them too.

**Comment by cinnamoner** [comment]
@Elbullazul 
Now that you've got Mint 18 Final and the Budgie Remix, nothing holds you back. It might be useful to look into Solus itself though. Perhaps 1.0.0 will be a milestone. No need to rush it though. There's also the gtk issue, pointed out by Zerophaze. Thanks for reading through.

**Comment by cinnamoner** [comment]
@Elbullazul 
I've just noticed your "How to install from source / using the installer" description.

**Comment by cinnamoner** [comment]
@Elbullazul 
Fragmenting the thread is not my intention but I post them as they come. As previously stated, Budgie is essentially made up from the bricks of Gnome 3. As a matter of fact I would dare to say it's Gnome 3 done right. No offence to the fine people who favor Gnome 3 as is though. Personally, I would have taken it a step further and integrated Nemo for a file manager.

**Comment by cinnamoner** [comment]
@Elbullazul 
One little piece of advice, if I may. I would concentrate my efforts on the Windows 10 theme. After all, you haven't labelled it "the key theme" without a reason.

**Comment by cinnamoner** [comment]
@Elbullazul 
I don't wanna go to 34 again.

**Comment by feren** [comment]
Guys,
From what I've seen, the Cinnamon theme is practically done Windows 10 wise, just that it may need editing like any other theme would if Cinnamon actually gets vertical panels. Though about Budgie, the last time I checked something with GNOME 2 Panels (MATE), it had a Solid Black background, no transparency at all, so that might have to be addressed if it's the exact same story in Budgie (if it's even possible to make that panel semi-transparent)...

**Comment by Elbullazul** [comment]
well, since basic support is achieved, it's time to close this thread
