### ISSUE TITLE
gtk-3.20 file in wrong location

### ISSUE THREAD

**Issue by Zerophase** [Elbullazul/Windows-10#43]
In order to support multiple versions of gtk 3, the versions supported need to be located in the gtk-3.0 folder.

here's an example:
https://github.com/horst3180/arc-theme/tree/master/common/gtk-3.0

**Comment by cinnamoner** [comment]
@Zerophase 
Thank you. The multiple gtk issue always interests me. I hope it'll be addressed pretty soon. I've been thinking about crossing over to Arch or Manjaro but I fear I would easily brake it. Is there a failsafe or something? It might be a stupid question though.

**Comment by cinnamoner** [comment]
@Zerophase 
For example, how do you freeze your Cinnamon version, if you want to? No answer is answer still.

**Comment by cinnamoner** [comment]
@Zerophase 
For what it's worth, I would say this is the best issue in a long time.

**Comment by Elbullazul** [comment]
thanks for the tip!

I will make necessary changes then

@cinnamoner manjaro is very nice, and if you use it like you use Mint it shouldn't be a problem (unless you update everything to the newest version available)

I've been thinking about manjaro too

**Comment by bluedxca93** [comment]
on my pc just 3.20 instead of 3.0 works too.

**Comment by Elbullazul** [comment]
@Zerophase can you confirm that placing it in 3.20 really allows it to be read?

on gnome-look they say it's not working

on fedora 24 (ok, it's an alpha release but whatever) it doesn't work either

**Comment by cinnamoner** [comment]
@Elbullazul 
I'll take Zerophase's word anytime instead of Look's.

**Comment by Zerophase** [comment]
I could try deleting the 3.0 folder to see if just 3.20 works for reading the files. I think it makes more sense to have multiple versions in the 3.0 folder till the major distributions move up to 3.0.

Now, I do think there are still issues with the 3.20 settings. Not everything looks quite right.

**Comment by bluedxca93** [comment]
@zerophrase
have it outside the 3.0 folder in an 3.20 one and it works fine.
see: 
https://github.com/bluedxca93/Ambiance-blx-3-20

**Comment by cinnamoner** [comment]
@ Guys 
Keep it up. This is important.

**Comment by Elbullazul** [comment]
@Zerophase any news?

**Comment by Zerophase** [comment]
Yeah, just put the 3.20 folder in the 3.0 folder and and gtk will find the right version to use.

**Comment by cinnamoner** [comment]
@Elbullazul 
Hmmm?
