### ISSUE TITLE
Another Off Topic Discussion (by request)

### ISSUE THREAD

**Issue by feren** [Elbullazul/Windows-10#44]
_Welcome to Chaos_
_No order or logic required_

**Comment by feren** [comment]
Here we go again... ;p

**Comment by feren** [comment]
Now with less lag. :/

**Comment by feren** [comment]
Man, Inspire doesn't half look awesome even on Android:
![2016_07_06_18 51 35](https://cloud.githubusercontent.com/assets/11057934/16628774/04448150-43ab-11e6-8f5d-b0c431a4c41c.png)
![2016_07_06_18 51 45](https://cloud.githubusercontent.com/assets/11057934/16628779/0851b880-43ab-11e6-9b95-e504693b728f.png)
![2016_07_06_18 52 01](https://cloud.githubusercontent.com/assets/11057934/16628785/0d16ae02-43ab-11e6-8f29-77165f9edfe3.png)

**Comment by bluedxca93** [comment]
@feren theme ok, but awesome or wonderful is another thing..

**Comment by Elbullazul** [comment]
Looks cool!  :D 

What's the theme app?

**Comment by feren** [comment]
It has no App yet. It's literally just a config of Nova Launcher! Would be nice if someone made it an icon pack though...

**Comment by cinnamoner** [comment]
@feren 
Thank you man. It pure oxygen. But please try to limit the number of screenies a little. Thank you man you're awesome.

**Comment by cinnamoner** [comment]
@feren 
What kind of icon pack would you need. Please describe it.

**Comment by cinnamoner** [comment]
@feren 
Some of the icons are good but the entire lacks aesthetic coherence. Different styles put together. It would be a disrespect from my part if I lied.

**Comment by feren** [comment]
Android icon set using the resources from the Inspire icon set. ;)

**Comment by cinnamoner** [comment]
@feren 
I need to think a little. Then I'll try to help.

**Comment by cinnamoner** [comment]
@feren 
So you like Android icons, righ?

**Comment by cinnamoner** [comment]
@feren 
No worries. As soon as I figure out what you're trying to do I'm sure there will be a solution. But you've got to take me slowly.

**Comment by cinnamoner** [comment]
1. Get rid of Android.

**Comment by Elbullazul** [comment]
@cinnamoner 

2. jailbreak your iPhone :smile: 

just kidding...

turns out that gnome-look is having a bit more feedback than what I thought...
https://www.gnome-look.org/p/1013490/
https://www.gnome-look.org/p/1013482/

**Comment by cinnamoner** [comment]
2. Why do you need this launcher?

**Comment by cinnamoner** [comment]
@feren 
3. If you're creating for the desktop, use Stark and Synapse.

**Comment by cinnamoner** [comment]
@feren 
4. If you want to discuss Feren OS, this off-topic thread is not suitable.

**Comment by cinnamoner** [comment]
@feren 
5. How many DEs do you want in Feren OS/Which/Why?

**Comment by cinnamoner** [comment]
Sorry, this is an example of why you shouldn't create for touch.

**Comment by cinnamoner** [comment]
@feren 
6. Pull in all the good Windows themes, the Mac theme + your theme.

**Comment by cinnamoner** [comment]
@feren 
7. Make use of your StyleChanger (definitely).

**Comment by cinnamoner** [comment]
and I shall continue after a sign from you. Look, I've been knowing you for long enough to know that you're tremendously gifted. Just focus on what's important and you'll succeed. No doubt about it. I trust you and I believe in you.

**Comment by cinnamoner** [comment]
@Elbullazul 
Coming from Look. Oh no! The guy listed all the gtk warnings. And he's on Sid! This is not the kind of feedback I need. The layout is still stupid. And you're work is still a product. No. No. No.

**Comment by cinnamoner** [comment]
@Elbullazul 
Oh no! Coming from Look again. They haven't made any progress at all. The https is in vain. Hey my theory is still that Look has been hacked. But they should've 're recovered by now. Is there any messaging at least. I refuse to log in.

**Comment by cinnamoner** [comment]
@feren 
Please show yourself. I wanna help. I hope I haven't offended you. I want Feren OS finalised asap.

**Comment by cinnamoner** [comment]
@feren 
I'vs just revisited your page and read the description. Everything seems to be perfect. It's based on Mint Cinnamon. All the good themes are included. And the themed is also included. 
Include Stark and Synapse, drop the launcher, drop Android icons, include those reviewed by Charlie. Vivaldi is included. That's good. I think WPS is included as well. Wellcomescreen included. Done deal. Just perfect. Call it final. Submit it to the reviewers.Perhaps a little more testing before though. All in all a Linux distro can't get any better than that. So it's just a matter of time now. You're logo is very nice. I see no problems. But drop Android, the launcher and include Stark and Synapse. I'm sure you'vs put a lot of love and time into it. Almost three. Final touches and you're done.

**Comment by feren** [comment]
Sorry, was asleep then, yes, I'm just mainly focusing on 2016.2 for now, then some other stuff...

**Comment by feren** [comment]
@cinnamoner You forgot ONE THING: BUG FIXING

Also, the Paper icon set is there to go with Adapta, a Material Design Inspired GTK Theme that is pretty well coded.

PS:
1. Nova Launcher is NOT MY LAUNCHER
2. That icon set in the picture is no icon set, just a test of Drag Icon > Edit...

**Comment by feren** [comment]
NOPE. THERE IS NO MESSANGING

**Comment by cinnamoner** [comment]
@feren 
Making a distro is no easy endeavour. Jacque has been doing it for years and it's only now that he's starting to do it right. Lindoz is fine although still has some shortcomings.
You have the advantage of the latecomer. By that I mean you can learn from the mistakes of others.
Okay then. We'll discuss it right here. Just have one thing clear: I would like to take it step by step and not get distracted by things not belonging to your OS. We need focus. In the late afternoon I'll be available (GMT+02).

**Comment by cinnamoner** [comment]
<iframe width="494" height="278" src="https://www.youtube.com/embed/VS7V6jEfJn0" frameborder="0" allowfullscreen></iframe>

**Comment by cinnamoner** [comment]
<iframe width="494" height="278" src="https://www.youtube.com/embed/VS7V6jEfJn0" frameborder="0" allowfullscreen></iframe>

**Comment by cinnamoner** [comment]
[](url)<iframe width="494" height="278" src="https://www.youtube.com/embed/VS7V6jEfJn0" frameborder="0" allowfullscreen></iframe>

**Comment by cinnamoner** [comment]
https://youtu.be/Cf8g728pyAs

**Comment by cinnamoner** [comment]
https://youtu.be/93MLmHOysC4

_Best fork of Gnome 3 to date_
Please Mint, detach from Canonical and build a base of your own!

**Comment by feren** [comment]
feren OS: Cinnamon (in the future, a fork called 'Zuro UI' (Name Not Final)
feren OS Light: LXDE (Yeah...)

**Comment by cinnamoner** [comment]
@feren 
Those are fine ideas. But fur now, consider what is realistically doable. There's a dedicated thread. Please do the exposee of Feren OS. Just a summary. Please use simple and plain English. It is not very urgent though. It seems I might be leaving to attend some duties. There's no telling when will I be back, unfortunately. Soon enough, I hope. Thank you.

**Comment by feren** [comment]
#ferenOS2016.2
New Look for Themer in the new release, aka: Updated Thumbnails and a new white version of the icon inside the UI...

**Comment by cinnamoner** [comment]
@feren 
I'm back from my duties. I've got a splitting headache though.
Good point. LMDE 2 aka Betsy 2 is definitely on my list of eligible distros.
So far, my list encompasses the following distros (the order isn't supposed to tell anything):
1. Mint 18 Cinnamon 
2. LMDE (Linux Mint Debian Edition) 2
3. Budgie Remix
4. Soulus (They've designed the Budgie DE and have a base of their own but still comparatively small appbase)
5. Manjaro Cinnamon (which is essentially Arch made easier to manage but still a rolling distro)
*******************************
"One-man-show" Disros:
1. Makulu Lindoz (he should've waited a little, but he said will renew the iso regularly)
And, Obviously, Feren OS is on my list as well (still to be released)
End of List (unless you have knowledge of some other excellent distro(s) I migh have missed )

**Comment by Elbullazul** [comment]
@cinnamoner you forgot AnemOS...

unless you've changed your mind on it

**Comment by cinnamoner** [comment]
@feren 
Yes, Budgie is a fork of Gnome 3. Haven't stated otherwise. Some say it's a derivative of Gnome 3 but hey, I don't care how it's clasified. I just like it. End of story.

**Comment by cinnamoner** [comment]
@Elbullazul 
No I haven't. I just don't know what happened with it. Maybe you have news from moihack? Although it's an Xfce, I've always liked it.

**Comment by cinnamoner** [comment]
@Elbullazul 
An other Xfce based off of Makulu Xfce 9 is Rocking Hoss. It's a jewel. Do you know it?

**Comment by cinnamoner** [comment]
@ Guys
I always fancy distros that have something like Makulu Constructor built in.
Mint used to have Mint Constructor but was pulled from the repo after having been abused by some guys. But it hasn't vanished though. It's been modified and is used by SolydKX. It's right here on Git.

**Comment by cinnamoner** [comment]
What the heck? I guess I'm talking in the desert.

**Comment by Elbullazul** [comment]
@cinnamoner not yet :smile:

**Comment by cinnamoner** [comment]
Not yet but pretty soon then.

**Comment by cinnamoner** [comment]
SystemBack is fine but is not really a constructor. Hard to build hardware-independent distro with it.

**Comment by cinnamoner** [comment]
Refracta and Remastersys gave birth to Makulu Constructor (constantly changing). Then Constructor was changed into Replicator (by Boyd, of course). Boyd is a brilliant guy. I like him a lot.

**Comment by cinnamoner** [comment]
Boyd is also mastering bash. Quite frankly, I've never encountered a man like Boyd. Look has broken communication. I must contact him via mail.

**Comment by cinnamoner** [comment]
@ Guys
_Behold the best Xfce ever_

http://www3.telus.net/someubuntufreebies/

**Comment by feren** [comment]
Oh my gosh, he's making the CinnXP Icon Set! Can't wait!
https://github.com/petrucci4prez/CinnXP/tree/icon_theme

**Comment by feren** [comment]
See ya later guys!

**Comment by feren** [comment]
I'm back.

**Comment by Elbullazul** [comment]
@feren would you like to have a launcher like in your concept?

![feren-concept](https://bn1301files.storage.live.com/y3mxicQCT4qDAl5uGFUAisKnRyTnFi_aB0nCGgDZLXY5HewAuaOLDyagYKW1_fqrZmJvXL11SdNr4zuC2BL7g1GkdsPNec6h_4i56CbfxMkCBHgEcEin9saxFMZI1XsP1veFtK2-DO0EAQ6jbMiihoTTi3hW3yMcfvdwTglqtk-OR4/App%20Menu%20Installing%20App.png?psid=1&width=800&height=450)

**Comment by cinnamoner** [comment]
@ Guys. I'm no fanatic. I don't oppose the idea of a launcher. But it's got to be enticing.

**Comment by feren** [comment]
Yes please! BTW, that page there is "Favourites", the All Apps menu would then be Categories like the Slingshot Launcher and then Search Results would be like Slingshot too... (The Favourites icon is in another concept)

**Comment by cinnamoner** [comment]
@feren 
I'm not just saying I want/like Feren OS to play niceguy. I'm serious. But hey, I've gotta focus.

**Comment by cinnamoner** [comment]
@feren 
No. I don't get it. I know Sling but ... too many words and too fast brakes communication. Take it easy.

**Comment by cinnamoner** [comment]
@feren 
What is what? Where from? What is it? Why? Slow down a little. I'm dense.

**Comment by cinnamoner** [comment]
@Elbullazul 
What is in the picture?

**Comment by cinnamoner** [comment]
I'll figure it out. Never mind. Carry on.

**Comment by cinnamoner** [comment]
@feren 
Yes 4prez is doing what you say. The key of his success is called method. He doesn't work chaoticly and manages his emotions well.

**Comment by cinnamoner** [comment]
@feren 
Okay. I've read your phrase all over again. I understand it now.

**Comment by cinnamoner** [comment]
@Elbullazul 
Yes, please.

**Comment by feren** [comment]
So we ARE not the only ones:
https://forum.opendesktop.org/t/can-you-bring-back-private-message/81

**Comment by cinnamoner** [comment]
@ferns
I never assumed we are the only ones. What are you celebrating though. Is there private messaging?

**Comment by cinnamoner** [comment]
@feren 
Hey, I guess I'm kinda difficult today. Please don't get upset with me.

**Comment by feren** [comment]
No, I was celebrating because more supporters of the idea = more chance of it coming back sooner. ;)

**Comment by feren** [comment]
See ya tommorow guys
#ferenCEONeedsSleepLikeAnyoneElseWould

**Comment by cinnamoner** [comment]
@feren 
Sleep well feren CEO. Some day there might exist even a Feren Corporation. One never knows.

**Comment by feren** [comment]
I'm back! Who knows hey? ;)

**Comment by cinnamoner** [comment]
@feren 
I've got all it takes. Are you well rested?

**Comment by feren** [comment]
Yes. ;)

**Comment by cinnamoner** [comment]
![21f8b97e-2fdc-11e6-9c0d-051e3a7365ba](https://cloud.githubusercontent.com/assets/15638605/16709433/7ecd2c54-4619-11e6-9da6-4ad42d98c5f5.png)
@ Guys
Major update to my list of eligible distros. Just look at that. In conjunction with a W7 theme, Xfce actually makes sense. Is it true that Debian has pulled Compiz from their repo?

**Comment by cinnamoner** [comment]
@feren 
How do you find it?

**Comment by feren** [comment]
Comfy, that's all to say. ;p

**Comment by cinnamoner** [comment]
@feren 
Nobody wants to take over your work. We just wanna help. But only if you want us to.

**Comment by cinnamoner** [comment]
> Comfy, that's all to say. ;p

@feren 
Please decode it for me.

**Comment by cinnamoner** [comment]
@feren 
Probably means: C'mon, I'm fine. As for the rest, I don't really understand coder slang.

**Comment by cinnamoner** [comment]
@feren 
Most people are shallow. As you well know, they will only see the surface. You've gotta give them a good surface.

**Comment by cinnamoner** [comment]
@feren 
Whatever.

**Comment by cinnamoner** [comment]
@feren 
I'm already a happy guy. I've got all I need and then some. I can only give. End of story.

**Comment by feren** [comment]
Ok, I will always accept and have help, sorry if I came out to be picky, I hope you got the reply on the "failed" one...

BTW, in the future, which Discussion shall I post Build updates to, this one, or the "failed" one? PS: Any progress on the menu @B00merang ?

**Comment by feren** [comment]
PS: I'm actually not kidding with the theme thing, I'm actually for real on having EVERY beautiful theme on the OS, but there again, you can't have to much otherwise the ISO might reach 4+GB which is a no copier for Fat32 Drives... Definetely not looking forward to 2017.X which might replace most current Unsplash wallpapers with others, I know every distro has done it, but, I'd bet most people love the current wallpapers, hey, at least it that happens, the Upgrade Script will then copy the background in use before it gets replaced to the user's Picture Folder.

**Comment by feren** [comment]
Just going to test the next build, give you enough time to think things through and read my comments, I may not be available for a while, so see you later today! :/

**Comment by feren** [comment]
I'm back are you guys ok now??

**Comment by B00merang** [comment]
Hey, I think you accidentally copied me into a conversation. I'm not
involved in any way haha I'm a student atm
On 10 Jul 2016 10:24, "feren" <notifications@github.com> wrote:

I'm back are you guys ok now??

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Elbullazul/Windows-10/issues/44#issuecomment-231579425>,
or mute the thread
<https://github.com/notifications/unsubscribe/AIGOy05b4NDLiGDKq9NZqE1HJd7nNsDDks5qULpogaJpZM4JGVRp>
.

**Comment by feren** [comment]
Ah oops, wrong B00merang! (>.<) (Darn it, there's b00merang.weebly.com, and then there's another b00merang! Never mind, sorry!)

**Comment by feren** [comment]
BTW, @cinnamoner , Yeah, ChaletOS does half have a good Windows 7 wanna-be theme included with it, that's if you got that theme from ChaletOS that is... (It definetely looks like it)

**Comment by feren** [comment]
PS: @B00merang , turns out you and I both are students too! :D

**Comment by feren** [comment]
(feren OS Live Session Update)
This is the Video Wallpaper feature in action, so far, it has issues with the panel (it goes in front of the panel most of the time)
![screenshot from 2016-07-10 12-32-23](https://cloud.githubusercontent.com/assets/11057934/16713554/9d9b3a1e-469a-11e6-8caf-de4e0a264974.png)

**Comment by bluedxca93** [comment]
@feren video wallpaper interesting feature..
aero for 16.10 by me is most likely done next month.
ambiance for 16.10 stable atm afaik.

**Comment by feren** [comment]
Video Wallpaper = Shantz's XWinWrap running MPlayer in Full Screen Mode, I got the script from here: http://gnome-look.org/content/show.php/Video+Wallpaper?content=128535

**Comment by bluedxca93** [comment]
@feren maybe you can try to use wmctrl. reminds me of stardock dream(s).

**Comment by Elbullazul** [comment]
@feren post updates here,  apparently the other thread is dead. 

Problems with icons?

**Comment by feren** [comment]
Icons: Not problems yet with Inspire, still trying to make a GIMP icon that suits the icon set while looking good too, also, rebased the icons to elementary to get ALL panel icons here and make programs complete with the icon set (besides that, it doesn't look that different to the old one, just need to resize icons, then boom, done.)

**Comment by feren** [comment]
@bluedxca
Is wmctrl a window manager, because if it is, it won't work due to Muffin already running?

**Comment by bluedxca93** [comment]
@feren https://www.freedesktop.org/wiki/Software/wmctrl/

The wmctrl program is a
UNIX/Linux command line
tool to interact with an
EWMH/NetWM compatible
X Window Manager.

**Comment by cinnamoner** [comment]
> Yeah, ChaletOS does half have a good Windows 7 wanna-be theme included with it, that's if you got that theme from ChaletOS that is... (It definetely looks like it)

@feren 
No, it doesn't definitely look like it. You might wanna look more attentively. It's AnemOS by moihack.

**Comment by feren** [comment]
Oh OK, then I don't know which Distro copied the other with that theme then. :p
I know it doesn't, that's why I said **wannabe** Windows 7 Theme... :)

**Comment by feren** [comment]
Yeah, when I tried Chalet OS 16.04 Live and tried a Win7 WM theme, it looked just like that WM Theme...

**Comment by cinnamoner** [comment]
@feren 
I started out in Linux by ChaletOS by Dejan though.

**Comment by feren** [comment]
Wow. I started Linux as an Ubuntu (via WUBI) user, was surprisingly well acquainted with the Unity UI (It was 12.04 LTS that I used)

Fun Facts:
1. I used it more than Windows surprisingly until...
2. ...Then I installed GNOME after making Ubuntu look like Win7 (I actually thought it was GNOME 2 before I actually used it) though in a surprise turn of events, I accidentely turned on Airplane Mode wandering WTH it was and well, it LITERALLY GOT STUCK ON "ON", oh, and Windows also had no WiFi afterwards AT ALL.

**Comment by cinnamoner** [comment]
@feren 
Do you breathe at all while posting?

**Comment by feren** [comment]
Yep, normal human instinct.

**Comment by feren** [comment]
From now on, feren OS updates will now have a header on top of the comment (That is

**Comment by feren** [comment]
Oops, must of pressed it whilst trying to type the previous comment, my bad.

**Comment by cinnamoner** [comment]
@feren 
Just kidding though. Have you read the description of the thread we're on right now?

**Comment by feren** [comment]
"No description provided"

**Comment by cinnamoner** [comment]
@feren 
Underneath the title.

**Comment by feren** [comment]
Hey @Elbullazul If you somehow blur the background behind the panel in 3.0 with something like an Extension for Cinnamon, I swere, I'll be the first distribution maker that puts it in feren OS and enables it, In some concepts, the bit behind the panel is always blurred! :D

**Comment by feren** [comment]
Err, I can't seem to find any other description on this thread... :confused

**Comment by feren** [comment]
You know what? I've got a better idea for feren OS Updates:
https://github.com/feren/ferenOSProjectUpdates/issues/1

**Comment by cinnamoner** [comment]
> apparently the other thread is dead.

@Elbullazul 
It seems alive to me. Man I was upset with feren the other day for turning the repo into a joke. I hope he's learning though.

**Comment by bluedxca93** [comment]
@cinnamoner i started linux with using knoppix. but switched soon to
pure debian, and then to gnome2/ubuntu.

@feren any change to add themes for pekwm ? have luna and aero themes
for it on my harddisk somewhere. its powerful once used with
compton.Combined with a panel its a very fast alternative to openbox
or metacity/muffin.

**Comment by cinnamoner** [comment]
> Err, I can't seem to find any other description on this thread... :/

@feren 
C'mon. You can do better than that. It's the very first post in this thread. I hope you can see my point. And drop the confusion emoji already. And "remember to always think twice" (by MJ).

**Comment by cinnamoner** [comment]
@bluedxca93 
Feren is a fine young man. It's just he's little hasty at times, isn't he?

**Comment by cinnamoner** [comment]
@feren 
I wanna see your sense of humour. And proof of maturity, please.

**Comment by cinnamoner** [comment]
@feren 
Please don't disappoint me again. It all depends on your reaction.

**Comment by cinnamoner** [comment]
@feren 
Who's testing who again?

**Comment by cinnamoner** [comment]
@feren 
Countdown. 59,

**Comment by cinnamoner** [comment]
@feren 
Time is running out ... reaction, please!

**Comment by cinnamoner** [comment]
> Err, I can't seem to find any other description on this thread... :/


@feren 
So, have you seen it or not? It's been a full hour.

**Comment by cinnamoner** [comment]
@feren 
Time is up. Congratulations! You've failed on both threads. I haven't enjoyed it at all.

**Comment by cinnamoner** [comment]
@feren 
Just kidding of course. Or maybe not. One never knows.

**Comment by cinnamoner** [comment]
@feren 
And remember: one can't change history by deleting posts.

**Comment by Elbullazul** [comment]
We're moving all discussions to a chat room : https://gitter.im/Elbullazul/Windows-10?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link

So non issue threads will be closed.  I've sent invitations to @feren @bluedxca93 @Zerophase and @cinnamoner so we should meet there soon.

**Comment by feren** [comment]
@cinnamoner 
1. WHY JUST WHY?
2. One, I was asleep (+ no WiFi) when you posted the countdown comment, and two, I do have a sense of humour, don't get me wrong, but I just don't get the joke this time 'round. (O_O)

**Comment by Elbullazul** [comment]
Ok, guys, let's leave it like this. 

I don't know what the hell happened while I was away, but it doesn't look (or sound) pretty.

Let's drop the weapons and unite as a team again, ok?

**Comment by cinnamoner** [comment]
> Seriously, guys, let's keep the repo simple & clean


@feren 
Thank you. That's all I want. It feels good to see my posts haven't been futile although they might have been somewhat extreme.

**Comment by cinnamoner** [comment]
> Let's drop the weapons and unite as a team again, ok?


@Elbullazul 
Absolutely. That's all I want.
