### ISSUE TITLE
v0.9.9 incorrect Checksum

### ISSUE THREAD

**Issue by romulo1984** [Elbullazul/Windows-10#47]
The correct checksum for v0.9.9 Dark Theme is
`56323d8bd8b4b1e20e6172150dd77836532fe31239ada7c7a4eb3f181b45100620156ad42db118f36f50dfecd6771356fa9cec6a152d79c7bf607b8b62dfb082`
and not
`6323d8bd8b4b1e20e6172150dd77836532fe31239ada7c7a4eb3f181b45100620156ad42db118f36f50dfecd6771356fa9cec6a152d79c7bf607b8b62dfb082`

**Comment by cinnamoner** [comment]
@romulo1984 
Hello to you. That might be caused by a number of factors. How do you know which is the correct one?

**Comment by cinnamoner** [comment]
@Elbullazul 
SHA256 would suffice. I've never managed to generate a collision.

**Comment by Elbullazul** [comment]
@romulo1984 that's correct, I must have missed it in the rush to upload everything.

thanks for your feedback!

**Comment by cinnamoner** [comment]
@Elbullazul 
That was one of the factors.

**Comment by cinnamoner** [comment]
@Elbullazul 
Yeah. You've missed the 5. Human error. Was it copypaste? Consider a better method.

**Comment by cinnamoner** [comment]
I don't know whether you can see my point but the string wasn't incorrect. It was incomplete. Big deal.

**Comment by cinnamoner** [comment]
@Elbullazul 
A SHA512 string is too long and futile. Consider SHA256, will you?

**Comment by cinnamoner** [comment]
Man, I guess everyone is an expert in checksums these days.

**Comment by Elbullazul** [comment]
Maybe I'll start using md5. Period.

**Comment by feren** [comment]
md5sum, command for Terminal in Linux, might save you the job...

**Comment by cinnamoner** [comment]
SHA1.

**Comment by cinnamoner** [comment]
@Elbullazul 
Nope. There's never a period. Let's meet in the middle: SHA256

https://forum.manjaro.org/t/improving-the-checksum-on-manjaros-download-page/4263

**Comment by cinnamoner** [comment]
https://github.com/Elbullazul/B00merang-Project/issues/12

@MichaelTunnel
I want your opinion.

**Comment by cinnamoner** [comment]
@MichaelTunnell
We want your opinion.

**Comment by MichaelTunnell** [comment]
I don't think it matters too much as long as the checksum is made an tracked properly but I'd prefer sha256 just because it's a better algorithm.

MD5 is kind of the standard and while it has been broken technically the effort involved in breaking it is extreme and requires collision approach.

Either MD5 or SHA256 will suffice but I'd prefer SHA256.

Here's an example of SHA256 sum from KDE Neon. http://files.kde.org/neon/images/neon-useredition/current/neon-useredition-20160713-1223-amd64.sha256sum

**Comment by cinnamoner** [comment]
@MichaelTunnell
Thank you. You've just saved the day. As you might have noticed, we suffer from Babeltower Syndrome.
@Elbullazul
I've been dealing with checksum theory and practice for years. But there you go. You've got yourself a second opinion. Proceed as you see fit. Thank you.
