### ISSUE TITLE
System Installer Icons for the set

### ISSUE THREAD

**Issue by feren** [Elbullazul/Windows-10#48]
If you resize this to 256x256, you can use this icon for ubiquity and system-installer:

![win8_upgrade_assistant_icon](https://cloud.githubusercontent.com/assets/11057934/16900102/31371f1c-4c0a-11e6-9a45-afd2a9993754.png)

(This is the icon used in Windows 8.X and Windows 10 on the system installer)

**Comment by Elbullazul** [comment]
Well thanks!  I remember searching for this icon but couldn't find it.  I'll include it as soon as I can

**Comment by feren** [comment]
BTW, if you resource hacker an ISO of Windows 8/10's ./setup.exe and then look in Icon Group, you can get the proper install icon in all the sizes.

**Comment by cinnamoner** [comment]
@feren 
I've wanted to bring that up myself. Thank you. Good eye you've got.

**Comment by cinnamoner** [comment]
@feren 
You don't need to use ResHack. Just visit the Windows 10 Icon Database by Bavo Luysterborg. But you might wanna see the readme.

**Comment by cinnamoner** [comment]
@feren 
Hey, both ico and png in all sizes. Do you want me to put up the link? Fair use, okay?

**Comment by feren** [comment]
For Fair Use Only (Converted by GIMP)
![windows 10 installer 1](https://cloud.githubusercontent.com/assets/11057934/16901498/ddfb3598-4c3d-11e6-9580-f906517de0e7.png)
![windows 10 installer 2](https://cloud.githubusercontent.com/assets/11057934/16901499/ddfcc39a-4c3d-11e6-8752-f79e7a208209.png)
![windows 10 installer 3](https://cloud.githubusercontent.com/assets/11057934/16901501/de0097d6-4c3d-11e6-8597-dfbbdd634701.png)
![windows 10 installer 4](https://cloud.githubusercontent.com/assets/11057934/16901502/de00f97e-4c3d-11e6-9c1c-b114b60d8311.png)
![windows 10 installer 5](https://cloud.githubusercontent.com/assets/11057934/16901500/de006856-4c3d-11e6-9561-1b6ea29ec5c4.png)
![windows 10 installer 6](https://cloud.githubusercontent.com/assets/11057934/16901503/de016788-4c3d-11e6-999e-970cc44c5f72.png)

**Comment by feren** [comment]
There ya go, might as well **re**close this now! :)

**Comment by cinnamoner** [comment]
@Elbullazul 
You've been avoiding me for days. I just want a straight conversation right here right now, shall we?
What the heck is going on? Speak your mind already.

**Comment by feren** [comment]
> Hey, both ico and png in all sizes. Do you want me to put up the link? Fair use, okay?

Yea, tried looking for it on the site, couldn't find it... :/

**Comment by feren** [comment]
> @Elbullazul 
You've been avoiding me for days. I just want a straight conversation right here right now, shall we?
What the heck is going on? Speak your mind already.

Last time he said he was having a busy day... :/

**Comment by feren** [comment]
BTW, as well as making this issue in the first place, I also gave Windows8Icons Windows 7's own Installer icon (Just seems to suit it better than 8's)

**Comment by feren** [comment]
*Just goanna reboot into a feren OS Build, may not be available for a little while...*

**Comment by cinnamoner** [comment]
Oh no! I must be nuts indeed!

**Comment by feren** [comment]
@cinnamoner 
Micheal responded! https://github.com/Elbullazul/Windows-10/issues/47#issuecomment-233189115

**Comment by cinnamoner** [comment]
I was trying to communicate with Elbullazul. No problem. I understand.

**Comment by Elbullazul** [comment]
@cinnamoner please understand,  I'm on vacation,  doing other stuff too,  I can't be on buy all day like I could before.  

Speak of what?  If it's for the sums I'll switch to sha256 next release

**Comment by cinnamoner** [comment]
@Elbullazul 

> please understand, I'm on vacation, doing other stuff too, I can't be on git all day like I could before.

No worries, I understand. Being on vacation and doing other stuff too seem a healthy thing to me. It's such a relief. I was starting to think I had upset you. I'm rather difficult sometimes but it comes with the territory.


> If it's for the sums I'll switch to sha256 next release

Well, I think you should indeed switch to SHA256.

Thank you and don't ignore the people who care. Have a good time on you vacation and definitely do other stuff as well. Hey, thanks for answering.

**Comment by cinnamoner** [comment]
@feren 
And greetings to you as well, Mr. Hayes.

**Comment by feren** [comment]
> @feren 
And greetings to you as well, Mr. Hayes.

Any you? Mr ... (I forgot)
