### ISSUE TITLE
ubuntu ppa ?

### ISSUE THREAD

**Issue by dontspamm** [Elbullazul/Windows-10#5]
are there any plans to add a PPA ?

**Comment by Elbullazul** [comment]
hi @dontspamm , I have no idea of how to build a PPA, but I'm very interested in having one. But, like I said, no idea of how. I may have a look at it now that you mention it.

**Comment by Elbullazul** [comment]
sorry, requires programming an installation script, and I'm not there yet. You may want to try Noobslabs's PPA : http://www.noobslab.com/2015/09/do-you-like-windows-10-look-but-love.html
