### ISSUE TITLE
Cinnamon-only Fork

### ISSUE THREAD

**Issue by cinnamoner** [Elbullazul/Windows-10#51]
> the fork I created for you is now REALLY outdated. I'll post a new version soon

@Elbullazul 
I'm holding my breath. 😨

_Make sure it's purged from anything not belonging to Cinnamon_

Much appreciated,
Cinnamoner

**Comment by feren** [comment]
I think he was talking about the SLINGSHOT fork when he said that (I think)...

**Comment by cinnamoner** [comment]
@feren Nope. It's about a Cinnamon-only fork of the keytheme.

**Comment by feren** [comment]
Ok

**Comment by cinnamoner** [comment]
😨

**Comment by Elbullazul** [comment]
Please be patient

**Comment by Elbullazul** [comment]
@cinnamoner  [Cinn10.tar.gz](https://github.com/Elbullazul/Windows-10/files/410826/Cinn10.tar.gz)

**Comment by cinnamoner** [comment]
@Elbullazul Thanks. Much appreciated.👍

**Comment by Elbullazul** [comment]
how's this going?
