### ISSUE TITLE
Brainstorming 

### ISSUE THREAD

**Issue by cinnamoner** [Elbullazul/Windows-10#52]
## Do you have a cool idea? Post it!

**Comment by cinnamoner** [comment]
Suggestion no. 1
Description: another concept for startmenu

@Elbullazul 
1) Go http://www.cybertronsoft.com/products/privacy-eraser/ (don't have preconceived ideas)
2) Download & install 
3) Look at the menu in the UI
4) Reflect
5) Make a startmenu based on that menu (you may need to rh the assets out of it)
6) It won't be the original W10 startmenu. It will be way more awesome.
7) If you don't install the app, there's no way to see what I am.

**Comment by feren** [comment]
One word about this 'Part 2' issue, WOW.

**Comment by cinnamoner** [comment]
@feren 
Install the abovementioned app, then tell us your opinion. Please & thank you.

**Comment by feren** [comment]
*Hopes this thing runs on WINE*

**Comment by cinnamoner** [comment]
> Let's hope this thing doesn't actually erase your privacy.

@feren Yeah, it's a figure of speech. It's an oxymoron, I think. Don't worry, it's no more of a spyware than any proprietary software.

**Comment by feren** [comment]
@cinnamoner 
Seems, very laggy, or maybe that's like that because slow animations in the application. Doesn't seem that really relevant to the Windows 10 theme UI-wise TBH.

**Comment by cinnamoner** [comment]
> Seems ...

@feren 
On my box, it ain't laggy at all. Try on Win.

**Comment by cinnamoner** [comment]
@feren 
Drag it down to the bottom left of the screen and you'll get the picture. I'm on a somewhat older build of it. It looks awesome. Use your imagination. It's got tremendous potential. I'll implement it no matter. I've just hopped for a little more enthusiasm.

**Comment by cinnamoner** [comment]
@feren 
Do you think one should try to replicate the but-ugly parts of W10 as well? Like it's startwhatever?

**Comment by cinnamoner** [comment]
@feren 
Hey, If you're not ready for what is awesome and if you're dogmaticaly into W10, I understand. No worries.

**Comment by feren** [comment]
@cinnamoner 
1. Man, no wander why mine may look different to yours
2. It was running on WINE, so yeah
3. Besides, let's just stick to what we were doing before, after all, don't want to swamp poor @NikoKrause with so many menu ideas do we??
4. I'm am ready for what is awesome, soon will be awesome though anyways. :)  (Just saying though still)

**Comment by cinnamoner** [comment]
Hey guys, a whole in a menu with an avatar in it is not a great innovation. Nor is an alphabetic stripe with a metro attached to it. W10 is nice, but the K-theme should outshine the original. I'm tinkering on it day n night. Imitation is the first step towards what I call the K-theme of the lineup. 
@Elbullazul You've got the skills, I've got the vision. Think about it. A mockery of W10 is not enough anymore. At least make the menu fantastic. I think you're broad-minded. So I'm sure I haven't offended you. Looking forward. Much appreciated.

**Comment by feren** [comment]
IDEA FOR K (@cinnamoner ): My colours, but, add a twist to the menu, add a gradient that gets darker towards the bottom of the menu starting with my Start Menu colour, and then on the panel, do something like Windows 7 does where there's a darker gradient on the left and right of the panel with the middle part being my taskbar colour

**Comment by cinnamoner** [comment]
@feren 
The theme has gotta step out from the shadow of the original. I think it can be done. My original concept aka the W10 menu stripped from the metro tiles is not enough. What do you think?

**Comment by feren** [comment]
I'd think go with the current style and then invent something else epic out of it (For example, my idea above where it's like the current one, but then add gradients to it like so, then give the corners of things a bit of rounding, etc).

Or, even become a theme creator in the Longhorn Repository, see if any of us manage to fix that dank close button width bug meaning that since it's longer than the others, it seems to cause Metacity bugs for the other buttons. :(

**Comment by cinnamoner** [comment]
@feren Think freely. We're the slaves of what we've been feeden with.

**Comment by feren** [comment]
@cinnamoner 
I am thinking freely, just, what I'm seeing as ideas like I shown above looks actually pretty frickin' awesomely creative and clean.

**Comment by cinnamoner** [comment]
@Elbullazul 
I don't want anything epic. I just want you to consider suggestion no. 1 on this thread. Okay? Nothing happens overnight. Let's compromise.

**Comment by cinnamoner** [comment]
@feren I want a derivative of the mainstream W10 theme as well. Call it fastring if you like it. Can I count on your help?

**Comment by cinnamoner** [comment]
@feren Put up a relevant instance of that eraser software so the guys might have an idea. It requires some imagination to envision what I mean though. I think a screenshot cannot capture the experience but let's give it a try.

**Comment by cinnamoner** [comment]
@Elbullazul Hey, just ideas, you know. Brainstorming.

**Comment by cinnamoner** [comment]
@feren 
@Elbullazul 
Hey, I think suggestion no. 1 is great but I'm in the wrong repo. This is W10. Perhaps in the b00merang repo, somwhere, huh?

**Comment by cinnamoner** [comment]
@Elbullazul Let then 10 be 10. The idea is suitable for another theme (which might turn out cooler than 10 itself). Yeah.
