### ISSUE TITLE
Windows 10 Dark Theme v0.9.9 (+AU) on GNOME Shell 3.20.3

### ISSUE THREAD

**Issue by brandleesee** [Elbullazul/Windows-10#55]
I am opening a new issue because I do not know if the following images go in [here](https://github.com/Elbullazul/Windows-10/issues/49) or [here](https://github.com/Elbullazul/Windows-10/issues/43).

Thus, the best way to explain my plight is pictorial. 

`GNOME Shell 3.20.3`

[Download used.](https://github.com/Elbullazul/Windows-10/archive/v0.9.9.tar.gz)

### Issues 

The following images are a comparison between Numix & Windows 10 v0.9.9.

- There are no 'bars' that encompass each drop-down menu to distinguish one menu from another.
- The lack of highlighting when about to select an option makes the experience a little confusing.
- When I deselect the Global Dark Theme, Windows 10 Dark becomes White/Light/Bright.

### Gnome Tweak
![screenshot from 2016-08-31 19-58-52](https://cloud.githubusercontent.com/assets/12674437/18140807/6afe6a90-6fb7-11e6-86df-732447e4e23e.png)
![screenshot from 2016-08-31 19-59-10](https://cloud.githubusercontent.com/assets/12674437/18140808/6b07b23a-6fb7-11e6-8365-1e7401056458.png)
## Note what happens when I switch off the Global Dark Theme
![screenshot from 2016-08-31 20-18-55](https://cloud.githubusercontent.com/assets/12674437/18141050/4c70deea-6fb8-11e6-89a1-a05b96228ef0.png)

### Selection Menu
![screenshot from 2016-08-31 19-59-31](https://cloud.githubusercontent.com/assets/12674437/18140809/6b12dc6e-6fb7-11e6-9c07-f9f79a2e70ca.png)
![screenshot from 2016-08-31 19-59-54](https://cloud.githubusercontent.com/assets/12674437/18140810/6b1ed686-6fb7-11e6-9708-ad228fcfd8d2.png)
## Note what happens when I switch off the Global Dark Theme
![screenshot from 2016-08-31 20-19-11](https://cloud.githubusercontent.com/assets/12674437/18141065/54768a9a-6fb8-11e6-90bc-7b0da550e55d.png)

**Comment by Elbullazul** [comment]
Can you post the link to the page where you got the download from? 

Also,  try the dark theme from here :  https://github.com/Elbullazul/Windows-10/releases/tag/v0.9.9

**Comment by brandleesee** [comment]
From the same link you submitted. The 4th download link.
![screenshot from 2016-08-31 22-55-28](https://cloud.githubusercontent.com/assets/12674437/18146059/0f22f490-6fce-11e6-94d8-5cfde81fdf07.png)

**Comment by Elbullazul** [comment]
Mmm, I think github didn't hacks the code as I expected.  Use the dark theme link.

**Comment by brandleesee** [comment]
Just used the dark theme link.
No change whatsoever. 
So those screenshots apply also for the first (i.e. dark) download link.

**Comment by Elbullazul** [comment]
Can you post the theme's gtk.css file content? 

It's in gtk-3.20

**Comment by brandleesee** [comment]
Sure, here it is:

/* search for rgba value important! 46, 52, 54 */

/* default color scheme */
@define-color bg_color #ffffff;
@define-color fg_color #4c4c4c;
@define-color base_color #ffffff;
@define-color text_color #4c4c4c;
@define-color selected_bg_color #cce8ff;
@define-color selected_fg_color #262626;
@define-color tooltip_bg_color #ffffff;
@define-color tooltip_fg_color #4c4c4c;
@define-color progressbar_color #06B025;

@define-color outline_color rgba(46,52,54,0.3);
@define-color txt_shadow rgba(255, 255, 255, 0.76923);

/* OSD colors */
@define-color osd_bg_color #f1f1f1;
@define-color osd_fg_color #ffffff;
@define-color osd_borders #8c8c8c;
@define-color osd_outline #eeeeec;
@define-color osd_txt_shadow rgba(255,255,255,0.1);

/* widget text/foreground color */
@define-color theme_fg_color #2e3436;
/*
text color for entries, views and content in general */
@define-color theme_text_color black;
/*
widget base background color */
@define-color theme_bg_color #ffffff;
/*
text widgets and the like base background color */
@define-color theme_base_color #ffffff;
/*
base background color of selections */
@define-color theme_selected_bg_color #cce8ff;
/*
text/foreground color of selections */
@define-color theme_selected_fg_color #262626;
/*
base background color of insensitive widgets */
@define-color insensitive_bg_color #fcfcfc;
/*
text foreground color of insensitive widgets */
@define-color insensitive_fg_color #8c8c8c;
/*
insensitive text widgets and the like base background color */
@define-color insensitive_base_color #ffffff;
/*
widget text/foreground color on backdrop windows */
@define-color theme_unfocused_fg_color #8c8c8c;
/*
text color for entries, views and content in general on backdrop windows */
@define-color theme_unfocused_text_color black;
/*
widget base background color on backdrop windows */
@define-color theme_unfocused_bg_color #fcfcfc;
/*
text widgets and the like base background color on backdrop windows */
@define-color theme_unfocused_base_color #fcfcfc;
/*
base background color of selections on backdrop windows */
@define-color theme_unfocused_selected_bg_color #d1d1d1;
/*
text/foreground color of selections on backdrop windows */
@define-color theme_unfocused_selected_fg_color #000000;
/*
widgets main borders color */
@define-color borders #aaaaaa;
/*
widgets main borders color on backdrop windows */
@define-color unfocused_borders #8c8c8c;
/*
these are pretty self explicative */
@define-color warning_color #f57900;
@define-color error_color #cc0000;
@define-color success_color #73d216;
/*
these colors are exported for the window manager and shouldn't be used in applications,
read if you used those and something break with a version upgrade you're on your own... */
@define-color wm_title shade(#2e3436, 1.8);
@define-color wm_unfocused_title #8b8e8f;
@define-color wm_highlight rgba(255, 255, 255, 0.8);
@define-color wm_borders_edge rgba(255, 255, 255, 0.8);
@define-color wm_bg_a shade(#e8e8e7, 1.2);
@define-color wm_bg_b #e8e8e7;
@define-color wm_shadow alpha(black, 0.35);
@define-color wm_border alpha(black, 0.18);
@define-color wm_button_hover_color_a shade(#e8e8e7, 1.3);
@define-color wm_button_hover_color_b #e8e8e7;
@define-color wm_button_active_color_a shade(#e8e8e7, 0.85);
@define-color wm_button_active_color_b shade(#e8e8e7, 0.89);
@define-color wm_button_active_color_c shade(#e8e8e7, 0.9);
@define-color content_view_bg #ffffff;

@import url("gtk-contained.css");

**Comment by Elbullazul** [comment]
Try this one: https://github.com/Elbullazul/Windows-10/files/318531/Windows.10.Dark.zip

**Comment by brandleesee** [comment]
After replacing with your download, I then did not have an option 'Windows 10 Dark' in Gnome-Tweak. 

![screenshot from 2016-09-01 08-21-10](https://cloud.githubusercontent.com/assets/12674437/18157345/1f2d2352-701d-11e6-8ca5-d34b2e014174.png)

So, I re-downloaded the dark theme - first option - from here : [https://github.com/Elbullazul/Windows-10/releases/tag/v0.9.9](https://github.com/Elbullazul/Windows-10/releases/tag/v0.9.9) and also your modified .zip file. Extracted both and poured the contents of your modified .zip file in the other (replacing).

The result was a white theme whether the Global Dark Theme was on or off.


![screenshot from 2016-09-01 08-33-27](https://cloud.githubusercontent.com/assets/12674437/18157607/cd541944-701e-11e6-9108-9fddad2cb21d.png)


![screenshot from 2016-09-01 08-32-55](https://cloud.githubusercontent.com/assets/12674437/18157606/cd515d80-701e-11e6-8ec3-13ef0d65cd20.png)

I alsoo noticed that the gtk.css is mostly #ffffff.

**Comment by Elbullazul** [comment]
@brandleesee I'm a very sorry, it's a packaging error from my part. I've been very busy, so last packages were fast compression without checking.

Corrected package coming soon...

**Comment by Elbullazul** [comment]
also, I wonder how the hell github replaced a file i uploaded with another (2nd link i posted)

**Comment by Elbullazul** [comment]
https://github.com/Elbullazul/Windows-10/releases/download/v0.9.9/Windows.10.Dark.v0.9.9.tar.gz

It's shure to work now

**Comment by brandleesee** [comment]
### Bless you, brother!

This is the result I wanted to achieve.

Thank you.

Some screenshots have comments because there are some minute things that I believe can be improved.

![screenshot from 2016-09-01 18-12-22](https://cloud.githubusercontent.com/assets/12674437/18175214/cdc189be-7070-11e6-98a2-fe379befb855.png)
![screenshot from 2016-09-01 18-18-55](https://cloud.githubusercontent.com/assets/12674437/18175223/cdff140a-7070-11e6-9e08-d7b48bb938ea.png)
![screenshot from 2016-09-01 18-19-06](https://cloud.githubusercontent.com/assets/12674437/18175225/ce0478c8-7070-11e6-8cec-c83c8c5b18f9.png)
![screenshot from 2016-09-01 18-19-41](https://cloud.githubusercontent.com/assets/12674437/18175226/ce144d48-7070-11e6-81d9-3478fea9c137.png)
![screenshot from 2016-09-01 18-15-51](https://cloud.githubusercontent.com/assets/12674437/18175224/ce03b7b2-7070-11e6-9248-a6bba8172352.png)
![screenshot from 2016-09-01 18-12-47](https://cloud.githubusercontent.com/assets/12674437/18175217/cdd792ae-7070-11e6-994d-64a412c8816d.png)
![screenshot from 2016-09-01 18-14-05](https://cloud.githubusercontent.com/assets/12674437/18175216/cdd18788-7070-11e6-9105-b7c1f0e4f7a8.png)

### Squashed Menu

![screenshot from 2016-09-01 18-13-28](https://cloud.githubusercontent.com/assets/12674437/18175215/cdcc89cc-7070-11e6-9d5e-b8f8ef3e5779.png)
Can the menus have some padding in between?

### Focus Inconsistencies

![screenshot from 2016-09-01 18-14-35](https://cloud.githubusercontent.com/assets/12674437/18175219/cdda837e-7070-11e6-9909-6e9db7c07a33.png)
When the window is focused the switches are dark grey/blue and the area is dark-ish. 

![screenshot from 2016-09-01 18-15-08](https://cloud.githubusercontent.com/assets/12674437/18175218/cdd9ab2a-7070-11e6-96bd-a85fb44187c0.png)
When not in focus the switches spring to life and become vibrant. The same goes for the window itself.

The 'Remove' buttons remain brightly coloured regardless of the focus. When not in focus, the text disappears....

I think when not in focus, everything becomes dark-ish but when focused, the window sort of brightens. In short, the reverse of the screenshots.

### 'Minus' button has a 'Close' symbol

![screenshot from 2016-09-01 18-16-43](https://cloud.githubusercontent.com/assets/12674437/18175220/cdf22af6-7070-11e6-831d-09c8e79b7424.png)
![screenshot from 2016-09-01 18-17-17](https://cloud.githubusercontent.com/assets/12674437/18175221/cdf588f4-7070-11e6-8bd0-3f10b2b1d9ec.png)

### White line

![screenshot from 2016-09-01 18-18-13](https://cloud.githubusercontent.com/assets/12674437/18175222/cdfa3412-7070-11e6-9e81-16519bf77a09.png)
![screenshot from 2016-09-01 18-49-28](https://cloud.githubusercontent.com/assets/12674437/18176197/ebd233f0-7074-11e6-8e76-9fb97c23e00a.png)


All windows have a white line at the very top. The best way to reproduce it was with the above picture where two white lines are visible. One for each window.

**Comment by Elbullazul** [comment]
taking good note on the issues

thanks for your feedback :)

**Comment by Zerophase** [comment]
Yeah, I think the best thing that could be done for the dark theme is using different shades of grey / black for the different parts of the menu.

**Comment by brandleesee** [comment]
I hope you do not mind if I add some more issues that I have noticed.

Just to be clear, this has become my default theme, so I can only post these issues once I encounter them. I am not hunting them down. Only reporting them when I notice them.

This time, however, I am including screenshots of the Adwaita (default) theme and also Numix. This only to better illustrate my point. I do not expect nor want Windows 10 Dark theme to just be a black version of the mentioned two themes.

### Terminal Menus

![screenshot from 2016-09-02 10-35-58](https://cloud.githubusercontent.com/assets/12674437/18197770/45e09876-70f9-11e6-8781-35bdd73250c3.png)
![screenshot from 2016-09-02 10-36-18](https://cloud.githubusercontent.com/assets/12674437/18197772/45ef72e2-70f9-11e6-9603-d03a1afff7b6.png)
![screenshot from 2016-09-02 10-33-52](https://cloud.githubusercontent.com/assets/12674437/18197771/45e3b646-70f9-11e6-9603-0c1ee2f1fa67.png)
Menus look squashed as, I believe,  the horizontal rules ` <hr> ` are not present.
Toggle Indicators and associated spaces are also missing (very good sign & empty placeholder).

### Hovering

Points to note:
- The Global Dark Theme for both Numix and Adwaita (default) were ON and applications duly restarted, but both simply did not _darken_.
- The Adwaita (default) theme did not render/display all tool options....
- To illustrate my point I used the Pinta package.

![screenshot from 2016-09-02 11-02-20](https://cloud.githubusercontent.com/assets/12674437/18198670/4f416ed2-70fd-11e6-9fd0-4f61da86664a.png)
![screenshot from 2016-09-02 11-01-03](https://cloud.githubusercontent.com/assets/12674437/18198669/4f3c3606-70fd-11e6-98ad-d0a9bca47d32.png)
![screenshot from 2016-09-02 11-05-43](https://cloud.githubusercontent.com/assets/12674437/18198671/4f463660-70fd-11e6-9b31-dd276c2eb056.png)
Can Windows Dark 10 have the buttons become a little more evident when hovered on, as presently it does not.
Also, the currently selected tool (Paintbrush) is not evident.

### Excessive space in Dash/Dock

Points to note:
- I use the [Dash-To-Dock](https://micheleg.github.io/dash-to-dock/) Gnome extension installed manually.
- Adwaita (default) and Numix do not have Shell themes by default, hence the lack of comparative screenshots.
- I can only provide the system default screenshot:

![screenshot from 2016-09-02 11-24-35](https://cloud.githubusercontent.com/assets/12674437/18199279/e26121b0-70ff-11e6-99a0-583ce0b3a296.png)
![](https://cloud.githubusercontent.com/assets/12674437/18175214/cdc189be-7070-11e6-98a2-fe379befb855.png)
Can the excessive space be shrunken?

![screenshot from 2016-09-02 11-27-07](https://cloud.githubusercontent.com/assets/12674437/18199359/388558d6-7100-11e6-8013-51cb2a91d600.png)
The above screenshot is the options I presently have from the Dash-To-Dock extension. This applies to both Default and Windows 10 Dark themes.

**Comment by Elbullazul** [comment]
phew, I didn't know we had so many inconsistencies in the theme!

thanks again for pointing these out

**Comment by brandleesee** [comment]
I'm feeling guilty now!

Also, I now have this when I run ` sudo nautilus `:

![screenshot from 2016-09-02 17-16-33](https://cloud.githubusercontent.com/assets/12674437/18208800/321a7914-7131-11e6-9c4d-78368de0ee64.png)

Just in case the following might be helpful, I am running a system with the following:

```
Distributor ID: Ubuntu
Description: Ubuntu Yakkety Yak (development branch)
Release: 16.10
Codename: yakkety

GNOME Shell 3.20.3

GNOME nautilus 3.20.2
```

**Comment by Elbullazul** [comment]
the error list is shure long! thank you again

unfortunately my OS went down (for the nth time) so it may be a couple of days till everything gets back in order and i can get those errors a look

**Comment by brandleesee** [comment]
welcome!
sooner or later that's what I'm expecting from mine
maybe I should switch to a proper rolling distro....

**Comment by Elbullazul** [comment]
@brandleesee all bugs fixed, except the minus icon with the latest release : 
https://github.com/Elbullazul/Windows-10/releases/tag/v0.9.9-AU

**Comment by brandleesee** [comment]
@Elbullazul testing as we speak (I write!)
screenshots coming shortly!

**Comment by brandleesee** [comment]
### Lovely! Oh boy!

Only a couple of issues and requests at the end of this post.

![screenshot from 2016-09-14 17-47-09](https://cloud.githubusercontent.com/assets/12674437/18519890/d9c52f2e-7aa5-11e6-9aed-1564dd34b66d.png)
![screenshot from 2016-09-14 17-47-28](https://cloud.githubusercontent.com/assets/12674437/18519891/d9c9d04c-7aa5-11e6-9e43-edfebb5c2e16.png)
![screenshot from 2016-09-14 17-47-54](https://cloud.githubusercontent.com/assets/12674437/18519892/d9cde51a-7aa5-11e6-90b0-c8ecfab41e14.png)
![screenshot from 2016-09-14 17-48-11](https://cloud.githubusercontent.com/assets/12674437/18519893/d9d42fd8-7aa5-11e6-9f6b-76517b928cfa.png)
![screenshot from 2016-09-14 17-51-09](https://cloud.githubusercontent.com/assets/12674437/18519897/d9ec3d3a-7aa5-11e6-927c-2780ba0f8a88.png)
![screenshot from 2016-09-14 17-48-47](https://cloud.githubusercontent.com/assets/12674437/18519894/d9db6eb0-7aa5-11e6-9643-4b7ad26f1584.png)
![screenshot from 2016-09-14 17-50-03](https://cloud.githubusercontent.com/assets/12674437/18519895/d9df8d42-7aa5-11e6-9092-1d006bc63ed0.png)
![screenshot from 2016-09-14 17-50-17](https://cloud.githubusercontent.com/assets/12674437/18519896/d9e41f2e-7aa5-11e6-8b5c-6e7c41e40061.png)
![screenshot from 2016-09-14 17-51-36](https://cloud.githubusercontent.com/assets/12674437/18519898/d9ed7a6a-7aa5-11e6-9df6-382f756c8410.png)
![screenshot from 2016-09-14 17-52-28](https://cloud.githubusercontent.com/assets/12674437/18519900/d9fc9176-7aa5-11e6-9764-f7cbd600b83a.png)
![screenshot from 2016-09-14 17-52-05](https://cloud.githubusercontent.com/assets/12674437/18519899/d9f6f964-7aa5-11e6-8835-6bdd518de8ad.png)

## [Request] 

Can the default grey background match the black(ness) of the shell?

If this is beyond the scope of your aims then please guide me on which instances of the css to change or whatever is required.

---

### Little change in selected tool and hovering
![screenshot from 2016-09-14 17-53-17](https://cloud.githubusercontent.com/assets/12674437/18519901/d9ffbc8e-7aa5-11e6-8444-cd65181d38de.png)


### Nearly invisible black font color
Extension used: [System Monitor](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet)

![screenshot from 2016-09-14 18-03-31](https://cloud.githubusercontent.com/assets/12674437/18519903/da08803a-7aa5-11e6-8ee9-aca7d056473f.png)


---

Downloaded v0.5 icons pack, thanks.

Seemingly unrelated request:
I recently had to install Kdenlive and was unhappy that by default it _[required](https://ubuntuforums.org/showthread.php?t=2327432)_ the installation of the **oxygen** icon pack. 
Can the required icons be created with a Windows-style spin so I can deplete oxygen?

---

**Comment by Elbullazul** [comment]
@brandleesee you can activate "global dark theme" to have a full black theme

I'll investigate those icons, thanks for the suggestion :)

**Comment by Elbullazul** [comment]
![screenshot from 2016-09-14 12-38-24](https://cloud.githubusercontent.com/assets/15310985/18523060/29c4337c-7a78-11e6-84a8-93f41939ac55.png)

found it, corrections coming in next release
or, if you want to change it now:
```css
.popup-menu .popup-menu-item:insensitive {
```
and change color to : 
```css
color: rgba(255,255,255,0.2)
```

**Comment by brandleesee** [comment]
Oh, you're right. Blackness mode activated! Thank you!
Thanks for checking the oxygen thing, too.
As for your fix, mine is already ` color: rgba(255,255,255,0.2) ` in fact:

```
		.popup-menu .popup-menu-item:insensitive {
			color: rgba(255,255,255,0.2); }
```

Shall I provide the css file or screenshots?

**Comment by Elbullazul** [comment]
it must be one of the nodes in that sector thas has color: rgba(0,0,0,X)

it's really close to that one, so you can check. I already forgot which line it was :/

**Comment by brandleesee** [comment]
Cheers! It was this one: ` .popup-menu .popup-inactive-menu-item:insensitive { ` 

On another note: ` sudo nautilus ` produces the following:
![screenshot from 2016-09-14 23-14-48](https://cloud.githubusercontent.com/assets/12674437/18530272/16d14cba-7ad1-11e6-902a-51faa236e3fd.png)

**Comment by Elbullazul** [comment]
more work for the developer! :smile: 

probably will fix them tomorrow, and released with the next version (hopefully 1.0.0...)

**Comment by brandleesee** [comment]
hahaha, he/you won't be happy because I'm gonna pile some more:
(for the sake of 1.0.0 I noticed something else)

## Scenario 1 - Common selection and mouse operations

### Here all good
![screenshot from 2016-09-15 00-36-35](https://cloud.githubusercontent.com/assets/12674437/18532563/21fd3426-7add-11e6-8d48-206a593f83a4.png)

### Here same
![screenshot from 2016-09-15 00-37-00](https://cloud.githubusercontent.com/assets/12674437/18532564/22085d1a-7add-11e6-9891-6d8bb1eefe1d.png)

### On right-clicking the thumbnail disappears completely
![screenshot from 2016-09-15 00-37-18](https://cloud.githubusercontent.com/assets/12674437/18532565/220c95ce-7add-11e6-95f7-8fd8d5852d7b.png)

## Scenario 2 - Opening a non-maximised application

### Here all good
![screenshot from 2016-09-15 00-39-43](https://cloud.githubusercontent.com/assets/12674437/18532566/22122d7c-7add-11e6-94f0-c787a6ff7c5b.png)

### If the focus switches to a non-maximised application (whether the file is selected or not), the thumbnail disappears completely
![screenshot from 2016-09-15 00-40-18](https://cloud.githubusercontent.com/assets/12674437/18532567/2212c1a6-7add-11e6-9417-aee546b2dfbc.png)

**Comment by Elbullazul** [comment]
does it happen with adwaita/numix?

**Comment by brandleesee** [comment]
## Adwaita
![screenshot from 2016-09-15 07-29-50](https://cloud.githubusercontent.com/assets/12674437/18539402/5c93400a-7b17-11e6-9410-02a73209c1b5.png)
![screenshot from 2016-09-15 07-30-21](https://cloud.githubusercontent.com/assets/12674437/18539403/5c969732-7b17-11e6-9498-80652be179ca.png)
![screenshot from 2016-09-15 07-30-36](https://cloud.githubusercontent.com/assets/12674437/18539404/5ca1bc5c-7b17-11e6-955a-9c177a276022.png)
![screenshot from 2016-09-15 07-31-42](https://cloud.githubusercontent.com/assets/12674437/18539405/5ca28876-7b17-11e6-8c73-146330b7f61e.png)
![screenshot from 2016-09-15 07-32-17](https://cloud.githubusercontent.com/assets/12674437/18539406/5ca833e8-7b17-11e6-913e-3c6088e93dea.png)

## Numix
![screenshot from 2016-09-15 07-32-58](https://cloud.githubusercontent.com/assets/12674437/18539407/5caa4c50-7b17-11e6-9833-0ca9f2f92cf7.png)
![screenshot from 2016-09-15 07-35-53](https://cloud.githubusercontent.com/assets/12674437/18539408/5cb20558-7b17-11e6-8313-65f66a08b50d.png)
![screenshot from 2016-09-15 07-36-13](https://cloud.githubusercontent.com/assets/12674437/18539409/5cb915d2-7b17-11e6-8eee-fd7f3a4498f4.png)
![screenshot from 2016-09-15 07-37-29](https://cloud.githubusercontent.com/assets/12674437/18539410/5cc1f846-7b17-11e6-9f41-86e4a967b90a.png)
![screenshot from 2016-09-15 07-37-53](https://cloud.githubusercontent.com/assets/12674437/18539411/5cc67a56-7b17-11e6-873a-a4a7d143ab86.png)

**Comment by Elbullazul** [comment]
@brandleesee it's strange because my code is a fork from adwaita's source code. it shouldn't happen, unless GNOME intentionnally left the bug in the source code... which I don't think they would.

it should be something with ```view:backdrop``` class, I'll investigate and post updates

**Comment by brandleesee** [comment]
Thank you. If there is any way that I can be of help please do tell.

**Comment by brandleesee** [comment]
Btw, I don't know if this helps but I had referenced it here as well: [NoobsLab](https://disqus.com/home/discussion/noobslab/do_you_like_windows_10_look_but_love_linux_here_are_windows_10_gtk_themes_for_you_noobslab_ubuntulin/#comment-2860558269).
This was about 20 days ago so this was already present in the non-anniversary update.
This is also another reason to think that it might not really be from W10D as we have both speculated.
I might be wrong.

**Comment by Elbullazul** [comment]
@brandleesee my guess is that it's a bug in the code. Adwaita and Numix both use SCSS, and their code range covers pretty much all possible nodes (even some that are very unlikely, as :focus:hover:selected:insensitive:backdrop), which isn't the case with my code, since I use CSS still, because it's cleanier and also more easy for people to understand than SCSS who almost looks like a mix of CSS with shell scripts!

**Comment by brandleesee** [comment]
I'd rather have a simple theme that I can customise with limited knowledge, so, yeah, I understand why yours is in CSS. So in this case, I guess it's 'happy hunting' then.

**Comment by Elbullazul** [comment]
yeah, except I know where the fish are bitin' :D

**Comment by brandleesee** [comment]
now we're talking!

**Comment by Elbullazul** [comment]
strange, I get:
![screenshot from 2016-09-15 10-44-00](https://cloud.githubusercontent.com/assets/15310985/18558594/51916142-7b39-11e6-9e81-effa48895b76.png)

**Comment by brandleesee** [comment]
Something with the Global Dark Theme switch, then?

![screenshot from 2016-09-15 18-45-52](https://cloud.githubusercontent.com/assets/12674437/18558964/68fa5ae6-7b75-11e6-9e91-07ef87143e24.png)
![screenshot from 2016-09-15 18-51-01](https://cloud.githubusercontent.com/assets/12674437/18558965/69023e0a-7b75-11e6-8d5f-ffbd5a52a69b.png)

**Comment by Elbullazul** [comment]
or somewhere the engine tries to "darken" the black color (impossible!) so it just fills the picture with black...

**Comment by Elbullazul** [comment]
here's the correceted file : http://pastebin.com/1xE9Ci70

just ovwerwrite all the gtk-contained-dark.css file. I had to add a dirty hex value, but at least you won't get than annoying bug : 
![screenshot from 2016-09-15 12-00-10](https://cloud.githubusercontent.com/assets/15310985/18560328/c435cdbc-7b40-11e6-93c3-6ba519ead6c7.png)

**Comment by Elbullazul** [comment]
...and I fixed the pinta thing, a class in gtk2 called "toolbutton"...

![screenshot from 2016-09-15 15-10-24](https://cloud.githubusercontent.com/assets/15310985/18566168/725fc0ac-7b58-11e6-9ca6-23ea2a751fdc.png)

gtkrc file code : http://pastebin.com/VqDCWbwV

**Comment by brandleesee** [comment]
Ole! All good. Thank you.

I noticed that the close button - depending on the application - gets a blue border ` onclick ` (besides becoming red). 

` onhover ` does not reproduce this bug.

Applications that do this are: [Nautilus](https://www.youtube.com/watch?v=H-vz0aANC_E) & [Gnome-Tweak](https://www.youtube.com/watch?v=ZSVYioHGxtE)

Applications that do not do this are: [Terminal](https://www.youtube.com/watch?v=Teb6XfpGXrk) & [Pinta](https://www.youtube.com/watch?v=fcz6wmZRV1E)

This was very difficult to produce in screenshots, including .gif, hence, YT.

**Comment by Elbullazul** [comment]
yeah, I saw it too sometimes, but I was busy fixing pinta

I'll check this today if I have time...

**Comment by Elbullazul** [comment]
fixed

**Comment by brandleesee** [comment]
I know I said otherwise (email) but consider this as my only issue with the latest Win 10 Dark build: 
![](http://i.imgur.com/yZdBpjE.png)
The best way to explain it is that because there is no border I am at times unable to identify where a window starts and stops.

Otherwise, you can see [here](https://github.com/brandleesee/ePSXe4Ubuntu) that I use W10D for my own projects.

**Comment by Elbullazul** [comment]
ok, will add to the to-do list

making an all-black theme seems to be harder than anything else :/
