### ISSUE TITLE
.

### ISSUE THREAD

**Issue by cinnamoner** [Elbullazul/Windows-10#57]
@feren Give it a title. This mobilecrap can't cache the other thread.

**Comment by cinnamoner** [comment]
@feren fereeeeen? Do you copy?

**Comment by cinnamoner** [comment]
@Elbullazul Do you copy? Any novelties?

**Comment by cinnamoner** [comment]
@bluedxca93 So, 3.20 is more robust. Have you figured out its syntax?

**Comment by cinnamoner** [comment]
Oops, it's 21:08 GMT+02 here. Guess feren has gone offline.

**Comment by bluedxca93** [comment]
@cinnamoner mostly.
its very close to 3.4 somehow.

**Comment by cinnamoner** [comment]
> mostly 

@bluedexca93 Okay, that's good. Thanks for answering.

**Comment by cinnamoner** [comment]
@ All   Be back tomorrow. I've got a meeting with AJ on YouTube.
