### ISSUE TITLE
Invisible Checkbuttons

### ISSUE THREAD

**Issue by aidanharris** [Elbullazul/Windows-10#58]
![checkbox](https://cloud.githubusercontent.com/assets/3309784/18338788/4915aab0-7593-11e6-8cc9-f64787ebbe22.png)

OS: Arch Linux / Antergos
DE: Cinnamon (I haven't checked to see if it occurs in other DE's but would assume so)
GTK3:

```
> pacman -Q --info gtk3
Name            : gtk3
Version         : 3.20.9-1
Description     : GObject-based multi-platform GUI toolkit
Architecture    : x86_64
URL             : http://www.gtk.org/
Licenses        : LGPL
Groups          : None
Provides        : None
Depends On      : ...
Optional Deps   : ...
Required By     :  ...
Optional For    :  ...
Conflicts With  : None
Replaces        : None
Installed Size  : 68.65 MiB
Packager        : Jan Alexander Steffens (heftig) <jan.steffens@gmail.com>
Build Date      : Wed 17 Aug 2016 21:47:22 BST
Install Date    : Thu 08 Sep 2016 06:47:07 BST
Install Reason  : Installed as a dependency for another package
Install Script  : Yes
Validated By    : Signature
```

I installed the package from the AUR [here](https://aur.archlinux.org/packages/gtk-theme-windows10/) and tried the Git version too. The problem exists in both packages.

**Comment by Elbullazul** [comment]
have you tried installing the theme locally (~/.themes) and renaming gtk-3.20 to gtk-3.0 ?

**Comment by Elbullazul** [comment]
any news?
