### ISSUE TITLE
Glitch with transparency in xfce4 panel widgets

### ISSUE THREAD

**Issue by Elbullazul** [Elbullazul/Windows-10#59]
@ochosi can you tell me how do you achieve transparent icons in your gtk2 theme for the system tray?

ex. : 
![screenshot_2016-09-11_20-55-22](https://cloud.githubusercontent.com/assets/15310985/18421904/1560a9f0-7862-11e6-8ab2-dda5c8f92429.png)

**Comment by ochosi** [comment]
Not entirely sure what you're referring to. Are those indicators or is that really the system tray? If the latter is the case, there's not really much you have to do, just change the transparency of the whole panel (not in the theme, but in the panel's preferences).

**Comment by Elbullazul** [comment]
sorry, I meant indicators. Here's what I get with one of my themes:
![screenshot_2016-09-12_13-26-28](https://cloud.githubusercontent.com/assets/15310985/18445640/882d631c-78ec-11e6-9e9c-a81d62b6445e.png)

**Comment by Elbullazul** [comment]
do you know how I can get indicators transparent then?
