### ISSUE TITLE
Noticed the Windows icon in Nemo doesn't show up.

### ISSUE THREAD

**Issue by Zerophase** [Elbullazul/Windows-10#6]
Looking at other picture of the theme I noticed in the file view selection in the upper right hand corner of Nemo isn't showing up.  I believe there's supposed to be a windows icon visible there. It looks like it's there but very faint, currently.

![fileicon](https://cloud.githubusercontent.com/assets/4284284/11872736/8c0e7a90-a49c-11e5-8a5d-a8e09d316ebe.png)

**Comment by Elbullazul** [comment]
Yes, I know, the theme was built for shell and on the favorites bar to the left, it was clearly visible (because bg was black)

I'll check if I can turn that icon blue or something.

Thanks for posting about this one.

**Comment by cinnamoner** [comment]
@Elbullazul 
Yeah, blue would be just fine. The kind of blue used for the start button logo in Brahim's (optimimized) theme.

**Comment by Zerophase** [comment]
@Elbullazul That's cool.

**Comment by cinnamoner** [comment]
@Elbullazul 
Just dropped in to reassure you that my interest for the theme is greater then ever. Please continue the good work. I am with you every step of the way. Thanks.

**Comment by cinnamoner** [comment]
@Elbullazul 
OKAY. I am looking at the bar indicating occupied space on disk in W10 file manager (the "real thing"). Wonder if that could be brought into Nemo somehow. Just looks cool. What do you think? Doesn't have to be perfect match just close enough.

**Comment by Elbullazul** [comment]
@cinnamoner can you include a screenshot of the feature you would like please? 

thanks,

**Comment by cinnamoner** [comment]
http://b00merang.weebly.com/uploads/1/6/8/1/16813022/3785536_orig.png

**Comment by cinnamoner** [comment]
Are you planning for a X-mas Edition?

**Comment by cinnamoner** [comment]
As for the color of icon the thread is all about: either the color I've just referred to or the color from W10 bootsplash. Both seem good choices to me but I trust your taste better.

**Comment by Elbullazul** [comment]
@cinnamoner I think the bootsplash color would be a nice one. 

As for the disk space stuff, I'm sorry, but there's no way to do that, unless we could somehow build a patch for nemo to add this feature.

**Comment by Zerophase** [comment]
It might be possible to make Gnome System Monitor prettier. We'd have to build a plugin to add that feature to nemo.

**Comment by cinnamoner** [comment]
@Elbullazul 
OKAY then. The W10 bootsplash color it is. Upon reflecting, I like it better me too.

**Comment by cinnamoner** [comment]
@Zerophase 
Yup. That's a Nemo specific suggestion, I agree.

**Comment by cinnamoner** [comment]
OKAY. Just coming from Otherstuff's. Guess what, he gave the theme a bit of coverage. On his favorite Mate DE. Not exactly what this thread is about (@Zerophase: let me be excused) but I'm glad to mention it. Of course, you might have already seen what I'm talking about. And what's up with you guys? Nothing obvious has been going on here for a whole day here. Maybe preparing for Christmas, like everyone, huh?

**Comment by cinnamoner** [comment]
As for the bar stuff in Nemo, that's not all that important. Let's just fix the icon the thread is about and whatever (@Elbullazul) you see fit. I've seen calendar issue again on Look or haven't I? Time to be in jolly mood guys. Christmas Edition ... rambling ... Cinnamoner out.

**Comment by Elbullazul** [comment]
@cinnamoner could you please attach a link? I would like to see that.

Well, Xmas edition would be nice if there was something new to add, until now versions after v0.8 are just bug fixes...

I've updated the calendar stuff, I'm now uploading the new files and cooking the new release on Git

To you @cinnamoner and to you @Zerophase a merry Christmas and a happy new year, thanks for your invaluable help! :)

**Comment by cinnamoner** [comment]
http://m.youtube.com/watch?v=056O13Hkgbg

**Comment by cinnamoner** [comment]
http://m.youtube.com/channel/UCQpkMe-SLNg0HwWCP3eeTxw

**Comment by cinnamoner** [comment]
Or just type otherstuff linux in You Tube.

**Comment by cinnamoner** [comment]
@Elbullazul 
So, what do you think 'bout the video. Might not be much but I find it relevant.

**Comment by Elbullazul** [comment]
@cinnamoner well, it's a little more visibility for the theme, but it's just that, visibility. Thanks for the link!

maybe for christmas I'll upload websites stats as a gift xD

**Comment by Zerophase** [comment]
@cinnamoner Thanks. Same to you. Yeah, the themes definitely good. It's pretty popular on Arch. I wouldn't solely rely on those gnome looks numbers.

**Comment by cinnamoner** [comment]
@Zerophase 
The Gnome Look numbers = 0 to me. My point exactly.

**Comment by cinnamoner** [comment]
@Elbullazul 
No need to convince me. I wouldn't have spent my time with a theme that is not exceptional. Just carry on and old Cinnamoner will be happy.

**Comment by cinnamoner** [comment]
@Elbullazul 
@Zerophase 
I haven't checked yet the icon the thread is about but I assume it's been dealt with elegantly.

**Comment by cinnamoner** [comment]
@Elbullazul 
What are you cooking? If I may.

**Comment by cinnamoner** [comment]
@Zerophase 
I downloaded 0.8.3 but I haven't got the opportunity to check it out. I've been mostly (still am) mobile lately. And I don't quite get it. Has the Nemo icon issue been solved or just the calendar. If it has and if not much trouble, could you please put up a screenshot with it. Just childishly curious how it's turned out. Thank you.

**Comment by cinnamoner** [comment]
@Elbullazul 
Idem. Thank you.

**Comment by cinnamoner** [comment]
From what I'm reading here, the much debated icon in Nemo is still cooking. Might be wrong though.

**Comment by Elbullazul** [comment]
Icon Pack v0.2.2 fixes this
