### ISSUE TITLE
W10 theme in conjunction with the Deepin DE

### ISSUE THREAD

**Issue by cinnamoner** [Elbullazul/Windows-10#60]
I know about the original Deepin distro, based on Debian unstable, if I'm not wrong. And if I'm not I just wonder why would one base it on the unstable. Yet another thing: I don't reside in China and as far as I know, updating it is awfully slow due to the lack of worldwide mirrors.
***
I also know about the Manjaro implementation of Deepin. But I'm somewhat reserved concerning Manjaro.
***
Was thinking about basing Deepin DE on well, Ubuntu. And then applying the K theme. It seems there's an specific icon package for it (right here on Git) ... I think you can get the idea. Seems like an inteteresting DE and we don't wanna overlook it @feren @Elbullazul, do we?

**Comment by Elbullazul** [comment]
according to wikipedia (?) it uses a fork of gnome 3, so it should be covered...

**Comment by cinnamoner** [comment]
@Elbullazul The Manjaro imp is produced by   ... just type Manjaro deepin into Git. Perhaps it's useful.

**Comment by cinnamoner** [comment]
@Elbullazul You once said you were thinking about Manjaro as well. Does it still holds true. Maybe they've improved cause Mint have certainly worsened. I'm holding the mouse and I don't know whether to click or not.

**Comment by cinnamoner** [comment]
@feren @bluedxca93 Is it hard/easy to put Deepin on Ubuntu?

**Comment by feren** [comment]
@Elbullazul That was before, now, it's its own DE and Window Manager, etc

**Comment by feren** [comment]
@cinnamoner Hard, you can only have Deepin DE on its own and then some apps like Store don't work either/don't install at first...

**Comment by cinnamoner** [comment]
@feren Correct on all matters.

**Comment by bluedxca93** [comment]
deepin has sources. cant they build on/with launchpad?

**Comment by cinnamoner** [comment]
@MichaelTunnell I'm satisfied with what I've got but what's your opinion on the latest Deepin 15.3 toy from China?

**Comment by cinnamoner** [comment]
I think we can't talk about deepin without trying it out, now can we?  I've just thought  it might be interesting for kids. And it's got Crossover. I've just seen a couple of videos and although it seems a capable little thing, it seemed limiting to me but perhaps I'm wrong.

**Comment by feren** [comment]
Lol, tried installing CrossOver Deepin on another OS, refuses to run on a non-Deepin distro!

**Comment by cinnamoner** [comment]
That doesn't surprises me. I wonder whether Deepin really works or is more of a headache than anything  else. Seems to bee working in Europe. Mirror thingy. I'll try to put up 2 vids that I kinda liked.

**Comment by bluedxca93** [comment]
https://mirrors.ustc.edu.cn/deepin/pool/non-free/d/deepinwine-qq/deepinwine-qq_7.1.14522deepin5_i386.deb

tried that?
but well its only wine too in this case so relax.

**Comment by cinnamoner** [comment]
WOW! http://youtu.be/BU2lTbg0Teg

**Comment by cinnamoner** [comment]
@feren Just how are you/What are you (pre)occupied with?

**Comment by cinnamoner** [comment]
@Elbullazul I'm taking a plunge into Deepin. Will even try to install the K theme. It seems Sid is only unstable by Debian's standards. Debian stable is kinda 2 years behind anything.
***
Then, I'll do the same on Solus.
***
Never installed the theme in Gnome offshoots. Hopefully, I'll manage.
***
I would've liked to go on with Cinnamon but Mint ruined it, unfortunately. Arch and Manjaro are out of question.

**Comment by Elbullazul** [comment]
@cinnamoner deepin is macOS on linux it seems...

**Comment by cinnamoner** [comment]
> tried that

@Bluedexca93 No, not yet but it seems promising. I will. Thanks.

**Comment by cinnamoner** [comment]
> deep in is macROs on linux it seems...

@Elbullazul Yeah, I understand. I will try the Mac theme on it as well.

**Comment by cinnamoner** [comment]
Burning the isos right away. Just checksumed them. Match.

**Comment by cinnamoner** [comment]
....

**Comment by feren** [comment]
@cinnamoner Three words, 'feren OS Stuff'

**Comment by feren** [comment]
@cinnamoner 
> macOS Theme

There's no macOS Theme in Deepin:
1. He's probably meaning the dock mode
2. There's still a Windows 7 mode option called 'Comfort'

**Comment by feren** [comment]
@cinnamoner To theme Deepin is a hard thing, you see, the only options you see on a fresh install will always be the only options no matter how many themes you may or may not have... :(

**Comment by feren** [comment]
OH MY GOD.
Just saw the Software Center in 15.3, too sad it won't work on non-Deepin distros... :(

**Comment by cinnamoner** [comment]
@feren 

> Just saw the Software Center in 15.3. 

Well yeah, it's the nicest I've ever seen myself. As previously stated, I've failed to install  Deepin.  Have you succeeded installing it or just seen the video?

**Comment by cinnamoner** [comment]
@feren Still receiving? It's around the time you use to go offline.

**Comment by cinnamoner** [comment]
@feren Don't worry, we'll clone that software center :)

**Comment by feren** [comment]
See ya guys

**Comment by feren** [comment]
@bluedxca93 RIP Zorin Menu...
http://zoringroup.com/blog/2016/09/19/this-is-zorin-os-12/

**Comment by feren** [comment]
@cinnamoner If you ever want to know what Themer will look like in GTK, look at this app:
http://zorinos.com/releases/12/images/ZorinAppearance.webm

**Comment by bluedxca93** [comment]
@feren they removed zorinmenu and awn. Reason was vala and future X
server migration.

**Comment by cinnamoner** [comment]
@Elbullazul I might port the W10 icons to Deepin using Oberon's nods.

**Comment by cinnamoner** [comment]
If MS would have implemented W8 as in Deepin, there's a fair chance the wouldn't have failed. Similarities : no start menu/something on the right (charmbar in W8; so much more in Deepin).

**Comment by cinnamoner** [comment]
@feren I'm thinking bout chatting with you on the Discuss channels.

**Comment by cinnamoner** [comment]
@feren Cloning the original Deepin Software Center is not impossible, hmmm? Just seeding an idea again. One never knows.

**Comment by cinnamoner** [comment]
Forget about Deepin.

**Comment by feren** [comment]
_This Discussion Is Now Abandoned (I guess)_
