### ISSUE TITLE
Windows 10 Light and QtCurve decorations

### ISSUE THREAD

**Issue by idontkn0w123** [Elbullazul/Windows-10#62]
The Window Borders with the minimize,maximize and close button don't work, not matter what I do.

Using Kubuntu 16.04.1 with KDE Plasma 5.6.5

**Comment by idontkn0w123** [comment]
![Uploading Screenshot_20160929_210352.png…]()

**Comment by Elbullazul** [comment]
have you followed the instructions here?
> http://b00merang.weebly.com/easy-installation-guide.html

**Comment by idontkn0w123** [comment]
Yes I did. But i can not select QtCurve theme in Point 4. So I do not see any borders of your theme :(

**Comment by idontkn0w123** [comment]
Here is an image of what I want to explain:

![screenshot_20160929_212008](https://cloud.githubusercontent.com/assets/22529375/18968772/ba841cb0-868a-11e6-91ea-abde761161d4.png)

**Comment by Elbullazul** [comment]
mmm, does qtcurve at leat shows up in appearance > style?

**Comment by idontkn0w123** [comment]
Yes. I was also able to get the kde menu and the bar at the bottom with your design. The Style is also imported.

![screenshot_20160929_213322](https://cloud.githubusercontent.com/assets/22529375/18969236/97d342b6-868c-11e6-89f2-a219ae82516c.png)

**Comment by Elbullazul** [comment]
mmm, weird.

anyways, give the old aurorae theme a try:
[Windows 10 Aurorae.zip](https://github.com/Elbullazul/Windows-10/files/501640/Windows.10.Aurorae.zip)
[Windows 10 Dark Aurorae.zip](https://github.com/Elbullazul/Windows-10/files/501641/Windows.10.Dark.Aurorae.zip)

**Comment by cinnamoner** [comment]
@Elbullazul Interesting to see feedback from the plasma desktop in conjunction with the K theme.

**Comment by Elbullazul** [comment]
@cinnamoner have you tried the theme on Plasma?

**Comment by idontkn0w123** [comment]
> mmm, weird.
>
>anyways, give the old aurorae theme a try:
>Windows 10 Aurorae.zip
>Windows 10 Dark Aurorae.zip
>
>   Manual from a file: Unpack the theme to the ~/.kde/share/apps/aurorae/themes/
>
>** can also be kde4

That isn't working too... :( I can now select the "theme" as window decoration but the same as the default decoration is loaded, as you see on the screenshot (Of course I did Apply):

![screenshot_20160930_081410](https://cloud.githubusercontent.com/assets/22529375/18982426/516dd232-86e6-11e6-85f0-785b11abf8d9.png)

**Comment by Elbullazul** [comment]
try saving the theme in the local user folder as posted with the links. It may be permission-related

**Comment by idontkn0w123** [comment]
no, all permissions were correct (755). But does not matter now, I'm using mate again. No Problems with your theme there :) 
plasma 5 full of bugs and is not stable at all... 

ty anyway for your help

**Comment by Elbullazul** [comment]
thanks to you for reporting this bug

kde is a pain for me, it's so hard to make things work right!

anyways, happy it works for you now :)
