### ISSUE TITLE
Preferences icon larger than others in drop down menus.

### ISSUE THREAD

**Issue by Zerophase** [Elbullazul/Windows-10#7]
In all of the right click menus the preferences icon is larger than the other icons in Cinnamon. To reproduce the issue go to themes, and turn on show icons in menus. Then right click an app for a drop down menu.

![menu_005](https://cloud.githubusercontent.com/assets/4284284/12244412/252343ac-b869-11e5-8e70-7080ebfb20e2.png)

**Comment by Elbullazul** [comment]
I'll have a look, I haven't really logged into cinnamon lately.

**Comment by Elbullazul** [comment]
Can you precise where's the file you right-click? I get this icon : 
![capture du 2016-01-11 17 23 51](https://cloud.githubusercontent.com/assets/15310985/12248567/476b0ade-b888-11e5-86e5-02ccb81f0c44.png)

**Comment by Zerophase** [comment]
I know it happens with quake, clipit, and shutter.

**Comment by Elbullazul** [comment]
This is my guake...
![capture du 2016-01-11 20 38 40](https://cloud.githubusercontent.com/assets/15310985/12252238/72a85aba-b8a3-11e5-943a-ffd231e520aa.png)

**Comment by Zerophase** [comment]
Hmm, I wonder if the icon pack didn't install correctly.

**Comment by Zerophase** [comment]
Alright, it's just the directory having the wrong name.

**Comment by Elbullazul** [comment]
Glad everything is ok :)
