### ISSUE TITLE
Cinnamon Settings' Icons and th2 update

### ISSUE THREAD

**Issue by feren** [Elbullazul/Windows-10#8]
Add icons for Cinnamon Settings and update most icons with the ones found in Windows 10 th2...

**Comment by Elbullazul** [comment]
Iyes, we've been thinking about this for a while. I'll try to find time to do it this week, but having to do it manually is very  time-consuming.

**Comment by cinnamoner** [comment]
@Elbullazul & @feren 

I'm interested in this myself.

**Comment by Zerophase** [comment]
I think there's a script that will parse, and rip icons from the windows installer. Not sure how legal making the icons that way is.

http://www.muflone.com/gextractwinicons/english/

**Comment by Elbullazul** [comment]
@Zerophase that sounds interesting, I'll have a look...

**Comment by Elbullazul** [comment]
Downloaded Icons from Icon8.com, let's see how this goes...

**Comment by cinnamoner** [comment]
Hi guys,

Following progress with great interest ...

**Comment by cinnamoner** [comment]
http://alternativeto.net/software/iconsextract/

**Comment by cinnamoner** [comment]
http://alternativeto.net/software/icofx/

**Comment by cinnamoner** [comment]
@Elbullazul 
Caution advised

**Comment by cinnamoner** [comment]
@Elbullazul 
Caution advised

**Comment by cinnamoner** [comment]
http://alternativeto.net/software/get-icons/

**Comment by cinnamoner** [comment]
http://www.ilovefreesoftware.com/29/featured/icon-extractor-software-for-windows-10.html

**Comment by cinnamoner** [comment]
http://www.howtogeek.com/109347/extract-high-quality-icons-from-files-using-a-free-tool/

**Comment by cinnamoner** [comment]
Or 30-day trialware:
http://icofx.ro/

**Comment by cinnamoner** [comment]
Disclaimer (aka chickening out): Well, of course, for research purposes only.

**Comment by Elbullazul** [comment]
No luck, just found ol' icons already included :(

as for the cinnamon settings, I'll have a look as soon as I can to it

**Comment by cinnamoner** [comment]
@Elbullazul 
Have a little patience. I might have an idea.

**Comment by Elbullazul** [comment]
@cinnamoner expose your idea, it might be helpful...

**Comment by cinnamoner** [comment]
@Elbullazul 
You haven't said what are the shortcomings of the app Zerophase had pointed to. As in 1); 2); 3); etc. Make sure you don't omit anything. Thanks.

**Comment by cinnamoner** [comment]
@Elbullazul 
IcoFX. Run a search ...

**Comment by Elbullazul** [comment]
@cinnamoner sounds useful, but I don't see where I would find time to do this except weekends. Thanks for the link b.t.w.

I'll try first to : 
1) Change the power buttons
2) Create tiles for Cinnamon Settings
3) Include more icons or diversify names to include more apps.

**Comment by cinnamoner** [comment]
@Elbullazul 
OKAY. That sounds good.

**Comment by Elbullazul** [comment]
Added support for Thunar icon... May not entirely work thought.

**Comment by cinnamoner** [comment]
@Elbullazul 
So, basically, you're saying that you've taken out a hammer and replaced it with a folder-like something. Okay, works for me!

**Comment by cinnamoner** [comment]
@Elbullazul 
I admit I like those icons but maybe you should consider creating an icon pack of your own. Something different but equivalently beautiful. Just a thought.

**Comment by cinnamoner** [comment]
@Elbullazul 
It will, eventually.

**Comment by Elbullazul** [comment]
![capture du 2016-01-26 09 02 00](https://cloud.githubusercontent.com/assets/15310985/12582572/fcfc20e8-c40b-11e5-9768-61fe96b75e8b.png)

*we're slowly progressing in our work. The old XP-like session buttons are gone!!!*

**Comment by cinnamoner** [comment]
@Elbullazul 
Interesting ...

**Comment by cinnamoner** [comment]
@Elbullazul 
https://github.com/Elbullazul/Windows-10/issues/9#issuecomment-174980774

**Comment by cinnamoner** [comment]
@Elbullazul 
I'm not saying those session buttons ain't good but consider looking at those in Makulu Aero 10. Just look at 'em. The choice is yours. On the other hand, I'll check what they look like in the Well-known.

**Comment by cinnamoner** [comment]
@Elbullazul 
http://1.bp.blogspot.com/-ob12Ebsm16o/VnB482O8O8I/AAAAAAAAK_Y/CdAhPSqYThM/s1600/menu.png

**Comment by cinnamoner** [comment]
Ugh ...
http://www.digitalcitizen.life/7-ways-shut-down-or-restart-windows-10-pc-or-device

**Comment by Elbullazul** [comment]
@cinnamoner Windows X has no log-out or sleep icons, that's why (I guess) they left the old XP-ones

I didn't like the logout button, I think I'll rather try to "flatten" they key icon from the original and reshape it a little

**Comment by cinnamoner** [comment]
@Elbullazul 
That's a good idea, yeah.

**Comment by Elbullazul** [comment]
![capture du 2016-01-29 14 22 01](https://cloud.githubusercontent.com/assets/15310985/12685670/bd35e20c-c693-11e5-82dc-d174304b1f3a.png)

look at the background and applets icons...

**Comment by cinnamoner** [comment]
@Elbullazul 
One step closer to "perfection". I'm sure you've put a lot of effort into it. Thank you. Makes me very happy.
@feren 
Well, how does it seem to you?

**Comment by cinnamoner** [comment]
@Guys?

**Comment by cinnamoner** [comment]
@Elbullazul 
I'll wait it out with patience. No need to rush it. But I expect excellence and I know you can do it.

**Comment by Elbullazul** [comment]
@cinnamoner it's already published here : https://github.com/Elbullazul/Windows-10/releases/tag/v0.9

Next builds will modernize stoke old icons and add some application icons

**Comment by cinnamoner** [comment]
@Elbullazul 
I knew the very second it appeared on Git. And is great work. From what I've gathered you do intentend to refine it even further. That's what I was referring to. My perfectionism is an annoyance to myself and to the people around me.

**Comment by Elbullazul** [comment]
nah, it's fine. Just enjoy the new icons :)

**Comment by feren** [comment]
Thanks, BTW, th2 introduced a new personalization icon so you may want to change the 'Themes' icon to that...

**Comment by cinnamoner** [comment]
@feren Nice to have you back.
@Elbullazul Maybe in 0.4, right? Are you planing for 0.4? I case you are, when to expect it?
@feren It's been a long time since I first read "th2". Please tell me what on earth "th2" stands for.

**Comment by Elbullazul** [comment]
@feren I'm working on it as well as new icons. ..

**Comment by Elbullazul** [comment]
@cinnamoner I guess it's second release (build 1511)

**Comment by Elbullazul** [comment]
![capture du 2016-02-14 18 06 27](https://cloud.githubusercontent.com/assets/15310985/13037053/b1d5db60-d345-11e5-8e58-c957dfa90bca.png)

@feren icons included, adding some more then releasing v0.4

**Comment by cinnamoner** [comment]
@Elbullazul 
Wow! Way better. I cannot contain my excitement.
By the way, I've figured out what "th2" stands for.

**Comment by cinnamoner** [comment]
@Elbullazul 
I'm very glad to know 0.4 is just around the corner. Take your time though. No need to rush it.

**Comment by cinnamoner** [comment]
@Elbullazul 
The applets and desklets icons don't illustrate what they should. Consider changing 'em.

**Comment by cinnamoner** [comment]
@Elbullazul 
Starting to look really good.
I understand your experimenting with gray but please no gray and no gray contextual menu in the final build. However, it's your brainchild and fell free to proceed as you see fit.

**Comment by cinnamoner** [comment]
> Windows 10 Transformation Pack - Technical Preview
 Elbullazul released this 18 days ago

@Elbullazul ?!

@Elbullazul Spelling out the checksums the way you did is a better approach than having 'em in a downloadable file. But it's advisable to spell out the name of the algorithm you use as well.

**Comment by cinnamoner** [comment]
http://mare-m.deviantart.com/art/Windows-10-Theme-for-Windows-7-500491733
http://sagorpirbd.deviantart.com/art/Windows-10-Themes-for-Win-7-Final-489257538
http://sagorpirbd.deviantart.com/art/Windows-10-Themes-for-Win-8-8-1-Final-527873187

@Elbullazul 
You're probably aware of those. I haven't checked 'em so I don't know whether they are fit as a source of inspiration or not. Probably Well-known itself remains the best source of inspiration.

**Comment by cinnamoner** [comment]
> The next release will be pitch white

@Elbullazul 
Nice figure of speech.
Obviously, there are an infinite number of whites. Arguably, the one used in Well-known is the best choice though.

**Comment by Elbullazul** [comment]
> it's advisable to spell out the name of the algorithm you use as well.
good point, I'll do that

I use "the real thing" for inspiration

**Comment by Elbullazul** [comment]
@cinnamoner Somewhere I read you asked for better applet & desklet icons. Your wish become true : 
![capture du 2016-02-17 11 06 30](https://cloud.githubusercontent.com/assets/15310985/13115850/7edff172-d567-11e5-8857-31bb1244e72f.png)

**Comment by cinnamoner** [comment]
@Elbullazul 
Applet & desklet icons are really awesome now. They are truly up to my expectations. Wasn't wrong about you. You never cease to amaze me. It is unbelievable that two icons can bring happiness into a person but they just have. I hope you're open to further suggestions. Not right now though. Thank you.

**Comment by cinnamoner** [comment]
@Elbullazul 
Okay. I can't help myself. Icons should unambiguously illustrate the words at the bottom. I won't get into details now but I will tomorrow. You're on the right track. I probably have all your tools but I lack your talent.

**Comment by cinnamoner** [comment]
@Elbullazul 
I don't have a global picture of Paramètres système but I'll give it a try, based on the dark shot and the white one. There it goes:
1. Économiseur d'écrain: beautiful icon but not really suggesting the concept of a screensaver. I admit this is a tough one.
2. Couleur: fairly good but consider putting those tiny little colored squares or color grid (whatever) on the screen of that monitor without changing the perspective on the monitor.
3. Langues in the white shot: beautiful icon but a globe and a watch doesn't really convey the concept of "Languages". The icon in the dark shot conveys it better.
4. Applications au démarrage: definite improvement in the white shot but still not quite there.
So those four icons need rethinking. As for the rest, some might need minor retouches. But Applets and Desklets are perfect.
I'm not criticizing. Just my arguable perspective. Again, it is hard (if not downright inappropriate) to express opinions 'cause it's under heavy development. But if you want to make it interactive (you should), then keep posting shots. And I would definitely value opinions coming from our friends present on this thread. And anyone else who cares. Thank you.

**Comment by Elbullazul** [comment]
@cinnamoner for the startup icon I took the one included in Win10. Plus, I never had a particular idea for that icon

The screensaver one will be tough! 

the other twos are already under transformation

**Comment by Elbullazul** [comment]
![capture du 2016-02-18 15 52 07](https://cloud.githubusercontent.com/assets/15310985/13157743/95568cea-d657-11e5-82af-a9d5cf539dfb.png)
how about this @cinnamoner ?

**Comment by cinnamoner** [comment]
@Elbullazul 
Truth to tell, I had a rough day and I've got a headache. But since you asked, there it goes: too much blue side by side and blue symbols on blue globe. Try to have an organic view. Look at the whole Paramètres système as you would look at a painting. I'll comment on every single icon tomorrow.

**Comment by cinnamoner** [comment]
@Elbullazul 
This is artwork not algebra. You're being too analytical. Try to think less and feel more.

**Comment by cinnamoner** [comment]
@Elbullazul 
I hope you're laughing 'cause it was partly meant that way.

**Comment by Elbullazul** [comment]
@cinnamoner I personally prefer the newer language icon.  v0.4 is just around the corner

**Comment by Elbullazul** [comment]
I thought I was finishing but I suddendly decided to add more icons...

**Comment by cinnamoner** [comment]
@Elbullazul 
Wise decision. Okay, let me have some coffee. I'll be back shortly ...

**Comment by cinnamoner** [comment]
@Elbullazul 
1. The "extensions" icon in the first two screenshots of Paramètres système, where you say:
"feren done! how do you like it?" is better.
2. Your latest "Languages" is OK, but those symbols on the blue globe shouldn't be blue. Try instead some kind of violet for 'em.
3. Your latest "Colors" icon is awkwardly overengineered. The previous one was better. I suggest just to put some color stripes on the screen of that tiny monitor. No need for that whatever in front if the tiny monitor.

**Comment by cinnamoner** [comment]
>  I suggest just to put some color stripes on the screen of that tiny monitor. 

If you so strongly want a color gradient, that's fine too. Just make sure you cover all the screen of the tiny monitor with it. Vertical color stripes are a better idea though (make sure you respect the order of wavelengths).

**Comment by Elbullazul** [comment]
@cinnamoner sorry, the language icon won't change, at least for the moment; it was too much work.
I'll reput the extension but with a flat gear.

color picture looks like this now :
![cs-color](https://cloud.githubusercontent.com/assets/15310985/13187480/3fee509a-d719-11e5-9724-7232202cb46c.png)

**Comment by cinnamoner** [comment]
@Elbullazul 
>  Try instead some kind of violet for 'em.

Take violet in a broader sense: violet, amethyst, indigo ... experiment ... has to look OK on the dark theme as well.

**Comment by Elbullazul** [comment]
![preferences-desktop-locale](https://cloud.githubusercontent.com/assets/15310985/13187647/6145d7b2-d71a-11e5-9725-110529132cc9.png)

@cinnamoner how about this?

**Comment by cinnamoner** [comment]
@Elbullazul 
Color icon is great now.

> I'll reput the extension but with a flat gear

That one sounds good.

> sorry, the language icon won't change, at least for the moment; it was too much work.

Fair enough.

Thank you. Your work is tremendously appreciated.

**Comment by Elbullazul** [comment]
thanks for the feedback @cinnamoner !

releasing in a few minutes v0.4 with 528 new or refurbished (?) icons!

**Comment by cinnamoner** [comment]
@Elbullazul 

> how about this?

Those symbols on the blue globe should not be blue as well. But proceed as you see fit.

**Comment by cinnamoner** [comment]
> releasing in a few minutes v0.4 with 528 new or refurbished (?) icons!

Great. Thank you man. You're awesome!

**Comment by cinnamoner** [comment]
@Elbullazul 
Is there something wrong with Git? 'Cause it says about latest release:

> Elbullazul released this 21 days ago · 3 commits to master since this release

**Comment by cinnamoner** [comment]
And about Technical Preview prerelease, it says:

> Elbullazul released this an hour ago

It's the other way around. Or am I missing something?!

**Comment by cinnamoner** [comment]
@Elbullazul 
Might be a glitch. I don't get it. It keeps updating the time but ... it's persistent.

**Comment by cinnamoner** [comment]
@Elbullazul 
It says the latest release was on Jan 29 and prerelease (Technical Preview) on Feb 19. Don't get it.

**Comment by Elbullazul** [comment]
Now that the point of this thread has been adressed, I'll close this issue. Thanks @feren @Zerophase @cinnamoner for your feedback and invaluable help!
