### ISSUE TITLE
opaque indicators xfce 4.12

### ISSUE THREAD

**Issue by isality** [Elbullazul/Windows-10#9]
Hello!

System indicators are grayed out. Can I make them transparent or black?

Theme: win10 dark.

Thanks.
![_2016-01-22_20-23-15](https://cloud.githubusercontent.com/assets/16147914/12517882/396ce576-c146-11e5-9f8d-e79171e09930.png)

**Comment by Elbullazul** [comment]
Yes, go to ~/themes/Windows 10/gtk-2.0/apps and open gnome-panel.rc

There you can edit hex values. Have fun :)

**Comment by isality** [comment]
Say the line number please. I could not find the line that refers to the color of the indicator.

**Comment by Elbullazul** [comment]
It's bg[PRELIGHT] = "#1f1f1f"

Change the hex value or remove the line and you're done.

**Comment by Elbullazul** [comment]
Hi there,

Would you mind sending a link to your WP? It looks very nice!

**Comment by isality** [comment]
https://drive.google.com/file/d/0B0Cx0i4f4frHUXdmWjZlckxPX0U/view?usp=sharing

**Comment by cinnamoner** [comment]
@isality 
Beautiful wallpaper. Do you have more of the like?

**Comment by isality** [comment]
@cinnamoner 
Maybe it will be interesting!

https://drive.google.com/open?id=0B0Cx0i4f4frHdFRiNDBxd0RSanc

**Comment by cinnamoner** [comment]
@isality 
Thank you very much.

**Comment by cinnamoner** [comment]
@isality 
I've just referenced. I hope you don't mind. Thanks again. We seem to share similar tastes.

**Comment by isality** [comment]
@cinnamoner 
It's my pleasure! Thanks.
